### ISSUE TITLE
Text translating/rendering x/y incorrectly when rotate > 0 from release 5.0.2+

### ISSUE THREAD

**Issue by marzolfb** [react-native-community/react-native-svg#242] opened 2017-01-26 07:23 UTC
Using react-native-svg 4.6.1:

![image](https://cloud.githubusercontent.com/assets/1242149/22323040/d7d033d6-e354-11e6-99d4-2a292b2e9ee1.png)

Using react-native-svg 5.0.2:

![image](https://cloud.githubusercontent.com/assets/1242149/22323083/1edac34a-e355-11e6-875a-68fe0542b32b.png)

Both using react-native 0.40.0.

Using this code snippet:

```
export default class rnsvgtest extends Component {
  render() {
    return (
      <View style={styles.container}>
        <ReactText style={styles.welcome}>
          react-native-svg testing
        </ReactText>
        <Svg
          height="300"
          width="300"
        >
          <Text
            fontSize="10"
            x="100"
            y="20"
            rotate="45"
            textAnchor="middle"
          >[100,20]</Text>
          <Text
            fontSize="10"
            x="150"
            y="20"
            rotate="45"
            textAnchor="middle"
          >[150,20]</Text>
          <Text
            fontSize="10"
            x="200"
            y="20"
            rotate="0"
            textAnchor="middle"
          >[200,20]</Text>
          <Text
            fontSize="10"
            x="250"
            y="20"
            rotate="0"
            textAnchor="middle"
          >[250,20]</Text>
        </Svg>
      </View>
    );
  }
}
```

**Comment by ElieMyIdea** [comment] 2017-08-31 09:39
+1

**Comment by msand** [comment] 2017-09-03 10:39
@marzolfb @ElieMyIdea Have you tried this? https://github.com/react-native-community/react-native-svg/pull/430

**Comment by ElieMyIdea** [comment] 2017-09-04 14:07
Unfortunatly,

 I'm on RN 0.39.2 with react-native-svg 4.4.1 but same problem appear..

**Comment by msand** [comment] 2017-09-13 22:36
Are you unable to upgrade RN? If you're able to get up to at least 
    "peerDependencies": {
        "prop-types": "^15.5.10",
        "react": ">=15.4.0",
        "react-native": ">=0.40.0"
    },
then you can use my "version": "5.1.7.3" from
https://github.com/msand/react-native-svg/tree/5.1.7.1
https://github.com/msand/react-native-svg/blob/5.1.7.1/package.json
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#2181798  
yarn add react-native-svg@https://github.com/msand/react-native-svg.git#2181798  
If you can get up to 
    "peerDependencies": {
        "react-native": ">=0.46.0",
        "react": "16.0.0-alpha.12",
        "prop-types": "^15.5.8"
    },
Then use 
npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67
yarn add react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67

**Comment by msand** [comment] 2017-09-13 22:38
otherwise, if get get in to a version below 0.46 but not compatible with 5.1.7.3, then use 5.2.0 or 5.3.0 from my fork

**Comment by dwilt** [comment] 2017-10-23 13:17
@msand I see #403 got merged. Why is the problem still persisting? 

![image](https://user-images.githubusercontent.com/1065539/31890868-93105672-b7fc-11e7-92f7-f9e052861a1a.png)

```js
{labels.map(({ x, y, text }, i) => (
    <G
        key={`label-${i}`}
        rotate={5}
        origin={`0,0`}
    >
        <SVGText
            x={x}
            y={y + 5}
            fontSize={fontSize}
            fontWeight={fontWeight}
            textAnchor={`middle`}
        >
            {text.toUpperCase()}
        </SVGText>
    </G>
))}
```
*packge.json*
```json
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-svg": "^5.4.2",
```

**Comment by msand** [comment] 2017-10-23 15:03
@dwilt have you tried react-native-svg@6.0.0-rc1 ? The changes are merged into the 6.0.0 branch https://github.com/react-native-community/react-native-svg/tree/6.0.0

**Comment by dwilt** [comment] 2017-10-23 15:28
@msand Updated to `6.0.0-rc1` and now getting this:

![image](https://user-images.githubusercontent.com/1065539/31897721-2699a436-b80f-11e7-8e3a-a8b724f70936.png)

**Comment by msand** [comment] 2017-10-23 15:30
Interesting, could you try to find some value which is set / calculated to the string '1' and change it to the number {1} instead?

**Comment by dwilt** [comment] 2017-10-23 15:46
@msand working on it..

**Comment by dwilt** [comment] 2017-10-23 15:59
@msand I think we have a bug here. As a sanity check, cause I couldn't find my problem, I just updated my `render` method to this:

**Note the `strokeWidth="2.5"`**
```js
render() {
    return (
        <Svg
            height={300}
            width={200}
        >
            <Circle
                cx="50"
                cy="50"
                r="45"
                stroke="blue"
                strokeWidth="2.5"
                fill="green"
            />
        </Svg>
    );
}
```
which gives me this:
![image](https://user-images.githubusercontent.com/1065539/31899380-5127d4e4-b813-11e7-9c02-8583d660a8bd.png)

So I tried making it a number..
**Note the `strokeWidth={2.5}`**
```js
render() {
    return (
        <Svg
            height={300}
            width={200}
        >
            <Circle
                cx="50"
                cy="50"
                r="45"
                stroke="blue"
                strokeWidth={2.5}
                fill="green"
            />
        </Svg>
    );
}
```
And now this:
![image](https://user-images.githubusercontent.com/1065539/31899437-7b32cf0a-b813-11e7-8f40-64539500a26d.png)

**Comment by dwilt** [comment] 2017-10-23 16:00
Kind of crazy: 

```js
render() {
    return (
        <Svg
            height={300}
            width={200}
        >
            <G></G>
        </Svg>
    );

}
```
![image](https://user-images.githubusercontent.com/1065539/31899498-9ec4e5c0-b813-11e7-9151-8456bc9d6ed0.png)

**Comment by msand** [comment] 2017-10-23 16:23
Can you try cleaning your project in xcode, 
rm -rf node_modules
npm i
react-native run-ios

**Comment by dwilt** [comment] 2017-10-23 16:38
Cleaned:
![image](https://user-images.githubusercontent.com/1065539/31900854-b122fcb2-b817-11e7-8a75-6fae3562892e.png)

Deleted `node_modules`, ran `yarn`.. Same thing:

![image](https://user-images.githubusercontent.com/1065539/31901220-b8dca06a-b818-11e7-983b-5f62f3523f5c.png)

**Comment by dwilt** [comment] 2017-10-23 16:39
Cleaned: 
![image](https://user-images.githubusercontent.com/1065539/31901325-0d7096b8-b819-11e7-8f84-e4d270fea79b.png)

Deleted `node_modules`, ran `yarn` and same thing.

**Comment by msand** [comment] 2017-10-23 18:08
The latest commit in the 6.0.0 branch doesn't work with yarn, only with npm, because of a git submodule dependency which yarn doesn't install, try removing node_modules and install using npm instead of yarn

**Comment by msand** [comment] 2017-10-23 18:09
Otherwise, try to react-native init newproject and install react-native-svg@6.0.0-rc1 there

**Comment by dwilt** [comment] 2017-10-23 21:36
I just tried `npm i` and still not working. Damn. Also, noticed this error on sim launch:

```
CompileC /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/TextPathSpacing.o Text/TextPathSpacing.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dwilt/Documents/GitHub/dropcountr-react-native/node_modules/react-native-svg/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/dwilt/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/dwilt/Documents/GitHub/dropcountr-react-native/node_modules/.bin:/Users/dwilt/Library/Android/sdk/platform-tools:/Users/dwilt/Library/Android/sdk/tools:/Users/dwilt/.nvm/versions/node/v8.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/dw
ilt/Documents/GitHub/dropcountr-react-native/ios/build/Index/DataStore -iquote /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/RNSVG-generated-files.hmap -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/RNSVG-own-target-headers.hmap -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/RNSVG-all-target-headers.hmap -iquote /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/RNSVG-project-headers.hmap -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/cjs -I../../React/umd -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Products/Debug-iphonesimulator/usr/local/include -IPerformanceBezier -IQuartzBookPack -IQuartzBookPack/Bezier -IQuartzBookPack/Drawing -IQuartzBookPack/Geometry -IQuartzBookPack/Image -IQuartzBookPack/TextDrawing -IQuartzBookPack/Utility -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/DerivedSources/x86_64 -I/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/DerivedSources -F/Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/TextPathSpacing.d --serialize-diagnostics /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/TextPathSpacing.dia -c /Users/dwilt/Documents/GitHub/dropcountr-react-native/node_modules/react-native-svg/ios/Text/TextPathSpacing.m -o /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/TextPathSpacing.o


** BUILD FAILED **


The following build commands failed:

	CompileC /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGTSpan.o Text/RNSVGTSpan.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/DropcountrReactNative.app
Launching com.dropcountr.dev
com.dropcountr.dev: 27505

Process finished with exit code 0
```
Which is odd cause the app still fired up.

**Comment by dwilt** [comment] 2017-10-23 21:37
Just a thought.. a `react-native init` installs with `yarn`.

**Comment by dwilt** [comment] 2017-10-23 22:00
Just tried a `react-native init` and then added `react-native-svg@6.0.0-rc1` and it built succesfully. Add this markup:
```js
import Svg, {
    G,
    Circle,
    Text as SVGText
} from 'react-native-svg';

export default class App extends Component<{}> {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>
                    Welcome to React Native!
                </Text>
                <Svg
                    height={300}
                    width={200}
                >
                    <Circle
                        cx="50"
                        cy="50"
                        r="45"
                        stroke="blue"
                        strokeWidth="2.5"
                        fill="green"
                    />
                    <G
                        rotate={45}
                    >
                        <SVGText>
                            Hey
                        </SVGText>
                    </G>
                    <G
                        rotate={45}
                    >
                        <SVGText>
                            You
                        </SVGText>
                    </G>
                </Svg>
            </View>
        );
    }
}
```
And I'm getting this:
![image](https://user-images.githubusercontent.com/1065539/31914931-97971396-b844-11e7-9754-e09c91be2692.png)

**Comment by msand** [comment] 2017-10-24 09:16
@dwilt what version of react-native is that? is it a 0.50-rc? can you try this:
`npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#ec35a1e`

**Comment by msand** [comment] 2017-10-24 09:17
Did you try cloning https://github.com/msand/newproject/ and running `npm i` ?

**Comment by dwilt** [comment] 2017-10-24 09:30
@msand Here's the `package.json` after `react-native init test`:
```
{
	"name": "test",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-beta.5",
		"react-native": "0.49.3",
		"react-native-svg": "6.0.0-rc1"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-beta.5"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by dwilt** [comment] 2017-10-24 09:30
I did not try cloning your `newproject`. I will try that now.

**Comment by msand** [comment] 2017-10-24 09:32
I'm wondering, did you run react-native link after installing react-native-svg?

**Comment by dwilt** [comment] 2017-10-24 09:39
@msand `newproject` worked for me:

![image](https://user-images.githubusercontent.com/1065539/31935775-8f0122a4-b8a7-11e7-8f97-ea07532a50cb.png)

**Comment by dwilt** [comment] 2017-10-24 09:41
@msand shit, no I forgot that. Will redo that now. Didn't think of it cause we already had it installed.

**Comment by dwilt** [comment] 2017-10-24 09:41
Not sure if this matters...
```
rnpm-install info Android module react-native-svg is already linked 
rnpm-install info iOS module react-native-svg is already linked 
```
Going to give it a shot now

**Comment by msand** [comment] 2017-10-24 09:43
Otherwise, verify that libRNSVG.a is in the list of linked libraries in the xcode project

**Comment by msand** [comment] 2017-10-24 09:49
And, as you already got the newproject building and starting, you can test your use case there at least.

**Comment by dwilt** [comment] 2017-10-24 10:08
Still getting this after the `react-native link`:
```
** BUILD FAILED **



The following build commands failed:
	CompileC /Users/dwilt/Documents/GitHub/dropcountr-react-native/ios/build/Build/Intermediates.noindex/RNSVG.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGTSpan.o Text/RNSVGTSpan.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/DropcountrReactNative.app
Launching com.dropcountr.dev
com.dropcountr.dev: 48923
```

**Comment by msand** [comment] 2017-10-24 11:00
Can you try with this instead (should also work with yarn):
`npm install --save react-native-svg@https://github.com/msand/react-native-svg.git#5a01d67`

**Comment by dwilt** [comment] 2017-10-24 22:37
Still same error:

![image](https://user-images.githubusercontent.com/1065539/31971582-50d8b9fc-b914-11e7-9f6a-d71fd44e728b.png)

**Comment by msand** [comment] 2017-10-26 01:16
Try with the latest commit from the 6.0.0 branch:
`npm i -S react-native-svg@https://github.com/react-native-community/react-native-svg.git#6.0.0`
or
`npm i -S react-native-svg@https://github.com/react-native-community/react-native-svg.git#be8797b`
As I have in my fork of the git submodule example repo:
https://github.com/msand/react-native-svg-example/blob/6.0.0/package.json

**Comment by msand** [comment] 2017-10-26 01:19
At some point I had a similar issue, but can't remember specific reason, either changing commit or clearing packager cache, or cleaning the native build. I think some old code was used by xcode or the ios js side at least, can remember which one. Do you have the same issue in android?

**Comment by msand** [comment] 2017-10-26 01:22
Might have to restart xcode after installing using npm as well, the project might not be correctly loaded otherwise.

**Comment by boygirl** [comment] 2017-11-09 00:28
With `react-native-svg@6.0.0` rotated text is in the correct position relative to its anchor, but is rotated incorrectly. Rather than the entire string being rotated as expected, rotations seem to be applied to each individual character:
<img width="334" alt="screen shot 2017-11-08 at 4 18 50 pm" src="https://user-images.githubusercontent.com/3719995/32581940-16b69846-c4a1-11e7-96c7-bca69c249a56.png">

I'm rendering like so:
```
<Text {...props} (...transform}>
  <TSpan {...moreProps}>
    {content}
  </TSpan>
</Text>
```
Still impacting https://github.com/FormidableLabs/victory-native/issues/103

**Comment by msand** [comment] 2017-11-09 00:41
@boygirl It seems you might be mixing up the rotate attribute on text elements (per glyph list of rotation angles) https://www.w3.org/TR/SVG11/text.html#TSpanElementRotateAttribute
and the transform attribute (a list of transform definitions) https://www.w3.org/TR/SVG/coords.html#TransformAttribute
try changing to something like:
```
<Text {...props} transform={transform}>
  <TSpan {...moreProps}>
    {content}
  </TSpan>
</Text>
```

**Comment by boygirl** [comment] 2017-11-09 01:14
@msand Thanks for your help! Unfortunately, that change puts me back in the previous situation, where a translation seems to also be applied. In this case it moves the elements off the screen.
<img width="349" alt="screen shot 2017-11-08 at 5 06 13 pm" src="https://user-images.githubusercontent.com/3719995/32583367-16b46ba0-c4a8-11e7-82a7-42a09f912fb1.png">

that is with hardcoded `transform="rotate(45)"`. Is that the correct usage?

**Comment by boygirl** [comment] 2017-11-09 01:35
Easier to see what's going on with a 5 degree rotation:
<img width="364" alt="screen shot 2017-11-08 at 5 27 33 pm" src="https://user-images.githubusercontent.com/3719995/32583775-39250080-c4aa-11e7-925d-70207457b3ee.png">

Is the fix for this still in `@6.0.0-rc1`?

**Comment by msand** [comment] 2017-11-09 11:19
@boygirl You probably want a text/tspan element per label, rotate them while in the correct position relative to the origin, and then translate them into the correct positions / set their final origin.

**Comment by msand** [comment] 2017-11-09 11:21
@boygirl https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

**Comment by boygirl** [comment] 2017-11-09 17:32
@msand Yes, I already have a one text/tspan element per label which is positioned using `x`, `y`, `dx` and `dy` attributes. The props provided to the text and tspan elements are identical to those I am using to position labels in web version of the charting library I'm working on. Unfortunately, in the native version, adding a rotation to the text is also causing an unwanted translation. The situation is as described in the original issue, I was just under the impression that it was fixed in `v6.0.0`.

**Comment by msand** [comment] 2017-11-09 17:57
@boygirl At least in my tests it seems to be spec conformant, can you try making the same in a jsfiddle, git repo, Expo or something? https://jsfiddle.net/m126Lrqu/
In my RNSvgTests I have three examples of rotation:
https://github.com/msand/RNSvgTests/blob/master/src/components/Nested.js
https://github.com/msand/RNSvgTests/blob/master/src/components/baseline.js
https://github.com/msand/RNSvgTests/blob/master/src/components/RotateScale.js
They're implemented as cross-platform svg, using the svgs library, (server-side) rendering using next.js for the web and react-native for ios and android. So it's easy to ensure that the same svg structure and attribute values create the expected output in the evergreens.

**Comment by boygirl** [comment] 2017-11-09 18:07
@msand I notice that none of your examples have a rotation and an `x` and `y` greater than zero. I think that may be the failure case.

**Comment by boygirl** [comment] 2017-11-09 18:16
@msand here's a reproduction in a fiddle: https://jsfiddle.net/onm20qp2/

**Comment by boygirl** [comment] 2017-11-09 18:40
This might help demonstrate what I think it going wrong... For polar charts I'm translating everything to the origin of the chart. You can see how all the label rotations end up being rotations around that center point, even when I explicitly provide cx and cy to my rotations. Here are 45 and 90 degree rotations _applied to each individual label, not the group_
<img width="320" alt="screen shot 2017-11-09 at 10 30 49 am" src="https://user-images.githubusercontent.com/3719995/32623266-698a9d30-c53a-11e7-9f99-ea66ecf2d0d1.png">
<img width="329" alt="screen shot 2017-11-09 at 10 33 08 am" src="https://user-images.githubusercontent.com/3719995/32623268-6cb86c4e-c53a-11e7-88a5-596597d64fba.png">

**Comment by msand** [comment] 2017-11-09 19:01
Ah, I think the optional parameters for rotate aren't supported yet, so you will have to use this manual pattern replacement rotate(<a> <x> <y>) = translate(<x>, <y>) rotate(<a>) translate(-<x>, -<y>). And I think support for several instances of one type of transform definition in one transform attribute value string might be sketchy as well, so best to put that in three different nested elements / transform attribute. Or simply implement support for it in the javascript transform parser: https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractTransform.js
Alternatively, set x and y for the labels to 0, rotate them while at the origin using a transform rotate, and use a wrapping G element with a transform translate to put it into place.

**Comment by msand** [comment] 2017-11-09 19:15
The TransformParser needs to be rewritten https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractTransform.js#L18-L63
It should split the string per definition, reduce over them with an initial value of the identity matrix, and for each transform definition, multiply the accumulated matrix with a matrix corresponding to the transform, and warn if any definitions cannot be parsed.

**Comment by msand** [comment] 2017-11-09 19:19
At least the images correspond to rotate without the optional parameters, so, rotating about the (centered) origin 0, 45 and 90 degrees.

**Comment by msand** [comment] 2017-11-09 19:24
Is this the effect you're looking for?
https://jsfiddle.net/onm20qp2/1/

**Comment by msand** [comment] 2017-11-09 19:24
Same with one transform definition per element: https://jsfiddle.net/onm20qp2/2/

**Comment by boygirl** [comment] 2017-11-09 19:56
Phew, okay thanks! I thought I was going nuts. I'll use an explicit matrix transform for now. Thanks!

**Comment by msand** [comment] 2017-11-09 21:06
Great! Happy I could help. nested & combined transforms can be a bit tricky at first, but, once you think of them as affine transforms in 3d using matrices and what order they're multiplied, it suddenly becomes almost trivial. Just have to get the order right ;)

**Comment by boygirl** [comment] 2017-11-09 21:51
@msand Thanks again for your help. This difference between rnsvg and the web svg spec really should be documented, IMO.

**Comment by msand** [comment] 2017-11-14 01:06
@boygirl I've made a pull request with a new transform parser, could you try it out, I haven't tested it properly yet. https://github.com/react-native-community/react-native-svg/pull/507

**Comment by boygirl** [comment] 2017-11-14 01:11
@msand yes, I'll try right now. Thank you so much!

**Comment by boygirl** [comment] 2017-11-14 01:21
@msand Yes, the new parser works correctly for me with rotations in the form `rotate(angle, x, y)` 🎉

**Closed** 2017-11-23 21:47 UTC
