### ISSUE TITLE
SVGs Rendering Differently / Wrong after upgrade

### ISSUE THREAD

**Issue by dl-husky73** [react-native-community/react-native-svg#1354] opened 2020-04-20 19:38 UTC
I have a map of markers and the SVG markers are all displaying differently, know detail just a color shade.  I have no idea what is causing this, I guess I will revert.  I tested the marker outside the map and had the same issue so it is RN SVG or transformer, not Maps.  

Included before and after pics.

It has worked for a long time until now. 
![snip1](https://user-images.githubusercontent.com/47721681/79792272-9b892200-831c-11ea-9985-12e996647c71.JPG)
![snip2](https://user-images.githubusercontent.com/47721681/79792283-a2179980-831c-11ea-8444-1d3fdd2c573f.JPG)

# Bug

[SVG Image In question.docx](https://github.com/react-native-community/react-native-svg/files/4510803/SVG.Image.In.question.docx)

#### Unexpected behavior
SVGs not correct.  Not all, about half. Seem images below.

## Environment info
RN 62.0
RN-SVG 12.1
RN-SVG-Transformer 14.3

**Comment by dschep** [comment] 2020-04-24 15:18
probably a duplicate of #1263.

**Comment by dl-husky73** [comment] 2020-05-01 16:05
Any updates here, still having this issue...

**Comment by dl-husky73** [comment] 2020-05-04 00:31
For anyone who wants to know, apparently something in a recent upgrade does not like pure black as a HEX.  Once we changed the color, all SVGs worked as they did in the past.   Weird problem but in case anybody else has the issue...

**Closed** 2020-05-04 00:33 UTC

**Comment by hemith** [comment] 2020-05-11 01:00
RN 61.5
react-native-svg@12.1.0

Same issue. 
Path without fill attribute --> white or transparent. NOT black

I solved this issue by using old version.
react-native-svg@10.1.0

**Comment by Veid** [comment] 2020-05-20 18:26
+1 also experiencing the same issue with black and path without fill attribute

**Comment by joebochill** [comment] 2020-06-23 17:11
I'm seeing the same where paths without fill attribute are appearing transparent. The break appears to be in the move from 11.0.1 -> 12.0.0
