### ISSUE TITLE
Version 7.0.X seems to be broken on Android

### ISSUE THREAD

**Issue by gbrlcustodio** [react-native-community/react-native-svg#781] opened 2018-09-17 02:31 UTC
It seems that version 7.0.x is broken on android, since it keeps throwing "_\<Element\> should be descendant of a SvgViewShadow_", as also pointed out by [here](https://github.com/react-native-community/react-native-svg/issues/273#issuecomment-421862836), is it a known issue?

**logcat outputs:**
`E unknown:ReactNative: RNSVG: com.horcrux.svg.ClipPathShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.ClipPathShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.PathShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.PathShadowNode should be descendant of a SvgViewShadow.`
`E unknown:ReactNative: RNSVG: com.horcrux.svg.GroupShadowNode should be descendant of a SvgViewShadow.`

Android version: **8.0.0**
React Native version: **0.57.0**

**Comment by msand** [comment] 2018-09-17 09:43
In the case of https://github.com/react-native-community/react-native-svg/issues/273#issuecomment-421862836 I think its some missing attributes causing exceptions making the view hierarchy fail. Should probably add some default values to be sent from js to native.
Could you post a full reproduction? or at least the component causing the exception?

**Comment by gbrlcustodio** [comment] 2018-09-17 13:01
Of course I can, but again, it works on older versions of this libraries.
```jsx
import React from 'react'
import Svg, {
  Defs, ClipPath, Path, LinearGradient, Stop, G,
} from 'react-native-svg'

const Background = props => (
  <Svg xmlnsXlink="http://www.w3.org/1999/xlink" viewBox="0 5 375 162" {...props}>
    <Defs>
      <ClipPath id="c">
        <Path data-name="Rectangle 39" fill="none" d="M0 0h375v162H0z" />
      </ClipPath>
      <LinearGradient id="d" x1={0.5} x2={0.5} y2={1} gradientUnits="objectBoundingBox">
        <Stop offset="0" stopColor="#fff" />
        <Stop offset="1" stopColor="#fff" stopOpacity={0.898} />
      </LinearGradient>
      <LinearGradient id="a" x1={0.5} x2={0.5} y2={1} gradientUnits="objectBoundingBox">
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <LinearGradient id="e" x1={1} y1={0.423} x2={0.176} y2={0.423} xlinkHref="#a">
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <LinearGradient id="f" x1={1} y1={0.381} x2={0} y2={0.381} xlinkHref="#a">
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <ClipPath id="b">
        <Path d="M0 0h375v162H0z" fill="none" />
      </ClipPath>
    </Defs>
    <G clipPath="url(#b)">
      <G data-name="Group 193" clipPath="url(#c)">
        <Path
          data-name="Path 133"
          d="M0 0h375v124.5l-223.742-.157-11.446-.632s-6.2-.47-12.425-1.1-12.29-1.434-12.29-1.434l-10.74-1.594-8.452 2.25-11.572 2.656-15.35 2.879-20.089 2.564-17.714 1.121-17.329-.282-13.857-1.631z"
          transform="translate(-1)"
          opacity={0.996}
          fill="url(#d)"
        />
        <Path
          data-name="Path 134"
          d="M610.553 387.468s-62-12.831-159.372 29.249-218.117-21.969-218.117-21.969V757.24h375.492z"
          transform="rotate(180 304.776 258.389)"
          fill="url(#a)"
          opacity={0.4}
        />
        <Path
          data-name="Path 135"
          d="M608.556 447.414s-103.73-50.322-217.3-30.706-158.188-41.954-158.188-41.954v402.462h375.488z"
          transform="rotate(180 304.276 268.377)"
          opacity={0.15}
          fill="url(#a)"
        />
        <Path
          data-name="Path 136"
          d="M158.465 404.4s65.859-46.648 198.272-8.8 253.7 24.38 253.7 24.38l-1 335.8H233.911z"
          transform="rotate(180 305.233 257.388)"
          fill="url(#e)"
          opacity={0.7}
        />
        <Path
          data-name="Path 137"
          d="M214 428.833s58.188-43.083 190.26-5.175S590.553 460 590.553 460l-1 326.378H213z"
          transform="rotate(180 294.776 272.691)"
          fill="url(#f)"
          opacity={0.7}
        />
      </G>
    </G>
  </Svg>
)

export default Background
```

**Comment by msand** [comment] 2018-09-17 21:30
Hmm. Seems to work fine here, are you giving it a width and height prop? As in e.g. 
```jsx
      <View style={styles.container}>
        <Background width="100%" height="100%" />
      </View>
```

<img width="1088" alt="screen shot 2018-09-18 at 0 27 18" src="https://user-images.githubusercontent.com/1131362/45651282-af81f780-bad9-11e8-9e25-b7fb753250ae.png">

```jsx
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import {
  LinearGradient,
  ClipPath,
  Defs,
  Path,
  Stop,
  Svg,
  G,
} from 'react-native-svg';

const Background = props => (
  <Svg
    xmlnsXlink="http://www.w3.org/1999/xlink"
    viewBox="0 5 375 162"
    {...props}
  >
    <Defs>
      <ClipPath id="c">
        <Path data-name="Rectangle 39" fill="none" d="M0 0h375v162H0z" />
      </ClipPath>
      <LinearGradient
        id="d"
        x1={0.5}
        x2={0.5}
        y2={1}
        gradientUnits="objectBoundingBox"
      >
        <Stop offset="0" stopColor="#fff" />
        <Stop offset="1" stopColor="#fff" stopOpacity={0.898} />
      </LinearGradient>
      <LinearGradient
        id="a"
        x1={0.5}
        x2={0.5}
        y2={1}
        gradientUnits="objectBoundingBox"
      >
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <LinearGradient
        id="e"
        x1={1}
        y1={0.423}
        x2={0.176}
        y2={0.423}
        xlinkHref="#a"
      >
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <LinearGradient id="f" x1={1} y1={0.381} x2={0} y2={0.381} xlinkHref="#a">
        <Stop offset="0" stopColor="#007aff" />
        <Stop offset="1" stopColor="#007aff" />
      </LinearGradient>
      <ClipPath id="b">
        <Path d="M0 0h375v162H0z" fill="none" />
      </ClipPath>
    </Defs>
    <G clipPath="url(#b)">
      <G data-name="Group 193" clipPath="url(#c)">
        <Path
          data-name="Path 133"
          d="M0 0h375v124.5l-223.742-.157-11.446-.632s-6.2-.47-12.425-1.1-12.29-1.434-12.29-1.434l-10.74-1.594-8.452 2.25-11.572 2.656-15.35 2.879-20.089 2.564-17.714 1.121-17.329-.282-13.857-1.631z"
          transform="translate(-1)"
          opacity={0.996}
          fill="url(#d)"
        />
        <Path
          data-name="Path 134"
          d="M610.553 387.468s-62-12.831-159.372 29.249-218.117-21.969-218.117-21.969V757.24h375.492z"
          transform="rotate(180 304.776 258.389)"
          fill="url(#a)"
          opacity={0.4}
        />
        <Path
          data-name="Path 135"
          d="M608.556 447.414s-103.73-50.322-217.3-30.706-158.188-41.954-158.188-41.954v402.462h375.488z"
          transform="rotate(180 304.276 268.377)"
          opacity={0.15}
          fill="url(#a)"
        />
        <Path
          data-name="Path 136"
          d="M158.465 404.4s65.859-46.648 198.272-8.8 253.7 24.38 253.7 24.38l-1 335.8H233.911z"
          transform="rotate(180 305.233 257.388)"
          fill="url(#e)"
          opacity={0.7}
        />
        <Path
          data-name="Path 137"
          d="M214 428.833s58.188-43.083 190.26-5.175S590.553 460 590.553 460l-1 326.378H213z"
          transform="rotate(180 294.776 272.691)"
          fill="url(#f)"
          opacity={0.7}
        />
      </G>
    </G>
  </Svg>
);

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Background width="100%" height="100%" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#ecf0f1',
  },
});

```

**Comment by gbrlcustodio** [comment] 2018-09-19 05:57
Which android version are you testing against? I did the test again with android 8 (real device, not an emulator) and react-native-svg 7.0.2 and it just cant work. But the same code, if I downgrade to 6.5.2 and rebuild, it works as expected.

**Comment by kristerkari** [comment] 2018-09-22 08:53
I just tested @msand's example on Android 8.0 and 5.0 emulators / RN 0.57 / react-native-svg 7.0.3. The app crashes and I am also seeing this with logcat:

```
08:50:02.335  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.
09-22 08:50:02.340  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.
09-22 08:50:02.343  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.PathShadowNode should be descendant of a SvgViewShadow.
09-22 08:50:02.352  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.PathShadowNode should be descendant of a SvgViewShadow.
09-22 08:50:02.369  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.GroupShadowNode should be descendant of a SvgViewShadow.
09-22 08:50:02.375  6745  6745 E unknown:ReactNative: RNSVG: com.horcrux.svg.GroupShadowNode should be descendant of a SvgViewShadow.
```

**Comment by alimek** [comment] 2018-09-27 11:18
i have the same problem when applied `LinearGradient` to my graph. Reverting to 6.5.2 fixed my problem.

RN 0.57.1

**Comment by msand** [comment] 2018-09-27 13:18
@gbrlcustodio  I only tested in the emulator so far, can you get it to work there at least?
@kristerkari @alimek  Please post a reproduction of the error or make your project available on github.

**Comment by alimek** [comment] 2018-09-27 16:01
Please check `https://github.com/alimek/react-native-svg-issue`

Failing on iOS and Android.
[How it should looks](https://ibb.co/bEEy7U) 
[iOS](https://ibb.co/fr8rSU)
[Android](https://ibb.co/h5c71p)

**Comment by kristerkari** [comment] 2018-09-28 20:07
> @kristerkari @alimek Please post a reproduction of the error or make your project available on github.

Here you go:
https://github.com/kristerkari/rn-svg-crash

I created a new React Native project, did a fresh install of react-native-svg and added the code from your example. Same results still, crashes in Android emulator for me.

**Comment by kristerkari** [comment] 2018-09-28 20:11
I also need to mention that downgrading to v6.5.2 fixes the crash for me.

**Comment by msand** [comment] 2018-10-10 22:47
Can you try with the latest commit from the master branch? At least it seems to work fine there.

**Comment by msand** [comment] 2018-10-10 23:39
A bit of the property update process has changed, and the error should probably be a warning instead, as in most cases it's because a new element has been created, and the new properties have been set on it, but it hasn't been attached to the svg render tree yet. At this point, the onAfterUpdateTransaction of the RenderableViewManager attempts to invalidate the svg root, but cannot find it, as the element isn't a descendant yet. I haven't been able to make it crash in combination with this error message yet, any help in how to trigger it would be useful.

**Comment by FibreFoX** [comment] 2018-10-11 16:34
@msand I added the commit https://github.com/react-native-community/react-native-svg/commit/b568a633edd27c4822ab3bca0ba98f2947526e10 via [patch-package](https://github.com/ds300/patch-package) and do not see the warnings anymore.

here my `patches/react-native-svg+7.0.3.patch` with another change for reducing gradle warnings:
```patch
patch-package
--- a/node_modules/react-native-svg/android/build.gradle
+++ b/node_modules/react-native-svg/android/build.gradle
@@ -49,5 +49,5 @@ repositories {
 
 dependencies {
     //noinspection GradleDynamicVersion
-    compile 'com.facebook.react:react-native:+'
+    api 'com.facebook.react:react-native:+'
 }
--- a/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewShadowNode.java
+++ b/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewShadowNode.java
@@ -257,7 +257,8 @@ public class SvgViewShadowNode extends LayoutShadowNode {
 
     int hitTest(Point point) {
         if (!mResponsible || !mInvertible) {
-            return -1;
+            // https://github.com/react-native-community/react-native-svg/commit/b568a633edd27c4822ab3bca0ba98f2947526e10
+            return getReactTag();
         }
 
         float[] transformed = { point.x, point.y };
```

Seems that this issue is fixed with that commit ;) maybe @kristerkari want to check this too? But my scenario might be different, as I do not use `<Defs>`, but I had the message too.

**Comment by kristerkari** [comment] 2018-10-11 16:44
Yeah I can try it out to verify the fix later tonight, but if someone wants to test out the fix before that you can use my repo for testing the fix from master (it has a clean install of React Native, react-native-svg and the code to reproduce the issue):
https://github.com/kristerkari/rn-svg-crash

**Comment by FibreFoX** [comment] 2018-10-11 19:04
@kristerkari you wrote about using Android 8 inside the emulator, but which image do you use? x86? x86_64? I'm not able to reproduce the crash. Do I have to do anything than trying to start the project?

**Comment by kristerkari** [comment] 2018-10-11 19:08
Yeah sorry I forgot to mention the emulator details.

It's this one:

Nexus 5X
1080x1920

Android 8.0 (Google Play)
API level 26
x86

**Comment by kristerkari** [comment] 2018-10-11 19:11
You should be also able to see [the previously mentioned errors](https://github.com/react-native-community/react-native-svg/issues/781#issuecomment-423728566) with `logcat` when running the app.

**Comment by kristerkari** [comment] 2018-10-11 19:17
Oh and one thing that seems to happen to me: it does not crash right away when I build the app, but does if I restart the app after that.

**Comment by kristerkari** [comment] 2018-10-11 20:09
So I just did more testing for the issue. Ignore my [previous comment](https://github.com/react-native-community/react-native-svg/issues/781#issuecomment-429084650). That was not the app crashing, but rather the "Pixer Launcher", so I got confused that the React Native app would have crashed.

Now that I tried to run the code again, I could not make the app crash with my https://github.com/kristerkari/rn-svg-crash repo, but the errors/warnings were still printed to `adb logcat` even with the latest master.

**Comment by msand** [comment] 2018-10-11 20:44
Ok, should perhaps just remove the error message, as in a lot (most) cases its expected behavior. Or make it discern this case and not even make the call.

**Comment by msand** [comment] 2018-10-11 21:04
@kristerkari I changed the null handling logic, so the common initial case doesn't cause any warnings: https://github.com/react-native-community/react-native-svg/commit/a2550c35df7cdf972ba707687480c7b4573c9b32

**Comment by kristerkari** [comment] 2018-10-11 21:07
I just tested and the warnings are gone now, thanks!

**Comment by msand** [comment] 2018-10-19 17:45
Closing this as it's fixed in the latest versions.

**Closed by msand** 2018-10-19 17:45 UTC
