### ISSUE TITLE
react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.

### ISSUE THREAD

**Issue by fengjr-tech** [react-native-community/react-native-svg#314] opened 2017-04-24 02:50 UTC
"react": "16.0.0-alpha.6",
  "react-native": "0.43.4",

react-native-svg@5.1.7 requires a peer of react@>=15.4.0 but none was installed.

**Comment by VincentFTS** [comment] 2017-04-24 09:09
duplicate of #305

**Comment by magicismight** [comment] 2017-05-02 04:01
Fix in 5.1.8

**Closed by magicismight** 2017-05-02 04:01 UTC

**Comment by getreup** [comment] 2017-07-25 18:12
That did not fix it since the dependency is now on react-native@0.44.0
