### ISSUE TITLE
LinearGradient rendering black

### ISSUE THREAD

**Issue by adamski** [react-native-community/react-native-svg#540] opened 2017-12-12 13:47 UTC
The following code does not render the gradient, but a black bar instead:

```svg
 <defs>
    <linearGradient id="screen_2-a" x1="-8.59%" x2="91.269%" y1="49.224%" y2="49.224%">
      <stop offset="0%" stop-color="#FFD300"/>
      <stop offset="100%" stop-color="#FFD930"/>
    </linearGradient>
    <linearGradient id="screen_2-b" x1="-.061%" y1="50%" y2="50%">
      <stop offset="0%" stop-color="#FFD300"/>
      <stop offset="100%" stop-color="#FFD930" stop-opacity="0"/>
    </linearGradient>
  </defs>
  <-- ... -->
    <rect width="33.03" height="239.74" x="175.38" y="442.73" fill="url(#screen_2-a)" fill-rule="nonzero"/>
    <path fill="url(#screen_2-b)" fill-rule="nonzero" d="M208.4,443.6 L208.4,681.09 C205.4,681.42 202.4,681.65 199.4,681.76 L190.4,681.76 C185.373772,681.570962 180.364132,681.069998 175.4,680.26 L175.4,444.43 C181.849496,443.372135 188.374323,442.840384 194.91,442.84 L194.91,442.84 C199.417355,442.840351 203.921127,443.094085 208.4,443.6 Z"/>

```
Any changes I can make to get this to work?

**Comment by adamski** [comment] 2017-12-12 16:08
I tried also with `stopColor` and `stopOpacity`, the above is from a AI exported -> Sketch saved SVG.

**Comment by dustinsavery** [comment] 2017-12-18 21:11
@adamski what platform are you seeing this on? Also, what versions of react-native and react-native-svg are you running?

**Comment by adamski** [comment] 2017-12-19 15:06
I was running RN 0.47, just updated to 0.51 and still seeing the same issue.
This is on iOS, running RNSVG 5.4.1.

**Comment by dustinsavery** [comment] 2017-12-19 15:58
Have you tried updating to `react-native-svg 6.0.x`?

**Comment by adamski** [comment] 2017-12-20 10:43
Failed to get 6.0.x working, 5.5.1 shows same issue.

**Comment by joshbroton** [comment] 2018-02-26 16:12
Good morning! I can confirm this problem is happening on `react-native-svg v6.1.0`. Gradients that rendered in older versions are black with no changes.

**Comment by msand** [comment] 2018-02-27 11:06
@adamski @joshbroton I tried making some small changes and it seems to work on both expo and latest react-native-svg:
https://snack.expo.io/@msand/-lineargradient-rendering-black-#540-fixed

**Comment by adamski** [comment] 2018-02-27 11:13
@msand I followed that link but couldn't see any code related to react-native-svg?

**Comment by msand** [comment] 2018-02-27 11:47
Strange, for some reason it reverts to the inital state when saving to my profile, try this: https://snack.expo.io/Bk6eSpGdG

**Comment by msand** [comment] 2018-12-09 01:55
Closing as this seems to be fixed/non-issue.

**Closed by msand** 2018-12-09 01:55 UTC

**Comment by samhv** [comment] 2019-06-09 00:25
instead of `stop-color="#FFD930"` use `style="stop-color:#FFD930"` an it will work

`<stop offset="100%" style="stop-color:#FFD930;"/>`

**Comment by du-hernandez** [comment] 2019-10-07 07:15
The following answer worked for me:
https://stackoverflow.com/questions/37962071/react-js-use-svg-linear-gradient-not-working
