### ISSUE TITLE
The follow svg not visible in android

### ISSUE THREAD

**Issue by OscarYuen** [react-native-community/react-native-svg#1127] opened 2019-09-30 17:47 UTC
The following Svg component becomes invisible in 9.9.9 version and this svg is visible in 9.5.1
```
<Svg width={25} height={30} viewBox="0 0 25 30" >
            <G id="App-Pages" stroke="none" strokeWidth="1" fill="none" fillRule="evenodd">
                <G id="Home" transform="translate(-327.000000, -50.000000)" fill={"#4A4A4A"}>
                    <G id="Share-button-Icon" transform="translate(327.000000, 50.000000)">
                        <G id="share">
                            <Path  fill={"#4A4A4A"} d="M4.71428571,10.2857143 C2.1147816,10.2857143 0,12.4004959 0,15 C0,17.5995041 2.1147816,19.7142857 4.71428571,19.7142857 C7.31378982,19.7142857 9.42857143,17.5995041 9.42857143,15 C9.42857143,12.4004959 7.31378982,10.2857143 4.71428571,10.2857143 Z M4.71428571,17.6190228 C3.26996141,17.6190228 2.09526295,16.4442684 2.09526295,15 C2.09526295,13.5557316 3.27001734,12.3809772 4.71428571,12.3809772 C6.15855409,12.3809772 7.33330848,13.5557316 7.33330848,15 C7.33330848,16.4442684 6.15861002,17.6190228 4.71428571,17.6190228 Z" id="Shape" fillRule="nonzero"></Path>
                            <Path  fill={"#4A4A4A"} d="M20.1428571,0 C17.543353,0 15.4285714,2.1147816 15.4285714,4.71428571 C15.4285714,7.31378982 17.543353,9.42857143 20.1428571,9.42857143 C22.7423613,9.42857143 24.8571429,7.31378982 24.8571429,4.71428571 C24.8571429,2.1147816 22.7423613,0 20.1428571,0 Z M20.1428571,7.33330848 C18.6985328,7.33330848 17.5238344,6.15861002 17.5238344,4.71428571 C17.5238344,3.26996141 18.6985888,2.09526295 20.1428571,2.09526295 C21.5871255,2.09526295 22.7618799,3.26996141 22.7618799,4.71428571 C22.7618799,6.15855409 21.5871814,7.33330848 20.1428571,7.33330848 Z" id="Shape" fillRule="nonzero"></Path>
                            <Path  fill={"#4A4A4A"} d="M20.1428571,20.5714286 C17.543353,20.5714286 15.4285714,22.6862227 15.4285714,25.2857422 C15.4285714,27.8852618 17.543353,30 20.1428571,30 C22.7423613,30 24.8571429,27.8852059 24.8571429,25.2856863 C24.8571429,22.6861668 22.7423613,20.5714286 20.1428571,20.5714286 Z M20.1428571,27.9047805 C18.6985328,27.9047805 17.5238344,26.7300751 17.5238344,25.2857422 C17.5238344,23.8414094 18.6985888,22.666704 20.1428571,22.666704 C21.5871255,22.666704 22.7618799,23.8414094 22.7618799,25.2857422 C22.7618799,26.7300192 21.5871814,27.9047805 20.1428571,27.9047805 Z" id="Shape" fillRule="nonzero"></Path>
                            <Rect  fill={"#4A4A4A"} id="Rectangle-path" fillRule="nonzero" transform="translate(12.428571, 10.714286) rotate(-32.893925) translate(-12.428571, -10.714286) " x={6.85714286} y={9.42857143} width={11.1428571} height={2.57142857}></Rect>
                            <Rect  fill={"#4A4A4A"} id="Rectangle-path" fillRule="nonzero" transform="translate(12.428571, 19.714286) rotate(-57.015526) translate(-12.428571, -19.714286) " x={11.1428571} y={14.5714286} width={2.57142857} height={10.2857143}></Rect>
                        </G>
                    </G>
                </G>
            </G>
        </Svg>
```

SVG Library Version: 9.9.9
RN Version: 0.59

**Comment by msand** [comment] 2019-10-03 06:53
Hmm, seems to work fine for me

**Comment by bydecker** [comment] 2019-10-03 14:12
Also having issues with SVG on Android. Rect seems to create problems.. replacing the Rects with Paths did the trick for us.

**Comment by elliotgeno** [comment] 2019-10-03 21:41
BIG bug with Rect in Android! Crashes apps. I had to replace with Path everywhere through the app to stop "random" crashes and non-renders.

**Comment by msand** [comment] 2019-10-04 06:49
Can you make a complete but minimal reproduction? I.e. a git repo with a new react-native project and the smallest amount of code that allows me to just git clone & yarn & react-native run-ios without any extra work to see the issue.

**Comment by bogrees** [comment] 2019-10-04 13:11
x3 on the Rect bug.  Any Svg component that includes a Rect component crashes the entire app on Android (iOS works fine).

Here is an example Svg that crashes the app.

` <Svg width="35" height="35" viewBox="0 0 50 50">
   <Rect x="12" y="12" width="26" height="26" fill="#fff" strokeWidth="2" rx="5" stroke="#aaa"/>
   <Path fill="#fff" stroke={checked ? "#000" : "#aaa"} strokeWidth="2" d="M17 12h16c2.8 0 5 2.2 5 5v16c0 2.8-2.2 5-5 5H17c-2.8 0-5-2.2-5-5V17c0-2.8 2.2-5 5-5z"/>
   <Path d="M16,23l7,7,l12,-12" fill="none" stroke="#222" strokeWidth="3" />
 </Svg>`

react-native: 0.59.8
react-native-svg: 9.9.2

We had to replace Rect's with Path's to get the app out, not ideal, but it worked.

**Comment by elliotgeno** [comment] 2019-10-04 13:47
Exactly what bogrees said, every single SVG that had a Rect component either blocked rendering of itself and sibling components OR crashed the app.

Here's another:
`<Svg viewBox="0 0 36 28" width="36" height="28">
	<Rect fill="#EBECED" width="36" height="28" rx="4" />
	<Path fill="#999999" d="M5.8,4.5L4,8.7h1.2l0.3-0.8h2l0.3,0.8H9L7.2,4.5H5.8L5.8,4.5zM6.5,5.5L7.1,7H5.9L6.5,5.5L6.5,5.5z M9.1,8.7V4.5l1.7,0l1,2.7l1-2.7h1.7v4.2h-1.1V5.6l-1.1,3.1h-0.9l-1.1-3.1v3.1L9.1,8.7L9.1,8.7z M14.9,8.7V4.5h3.5v0.9h-2.4v0.7h2.3v0.9h-2.3v0.8h2.4v0.9H14.9L14.9,8.7z M18.5,8.7l1.7-2.1l-1.7-2.1h1.3l1,1.3l1-1.3h1.3l-1.7,2.1l1.7,2.1h-1.3l-1-1.3l-1,1.3L18.5,8.7L18.5,8.7z" />
	<Rect fill="#d3d3d3" x="4" y="10" width="6" height="5" rx="1" />
	<Text x="30" y="15" fontSize="3" textAnchor="middle">1234</Text>
	<Text x="18" y="19" fontSize="3" textAnchor="middle" fill="#838383">3333 122222 60000</Text>
</Svg>`

**Comment by elliotgeno** [comment] 2019-10-04 13:57
Also, this happened after upgrading to Expo: "^35.0.0" in which react-native-svg was also upgraded to "9.9.2".

**Comment by msand** [comment] 2019-10-04 14:21
<img width="1680" alt="Screen Shot 2019-10-04 at 17 19 15" src="https://user-images.githubusercontent.com/1131362/66214835-211fea00-e6cb-11e9-9070-5b7fcbe797cb.png">

App.js
```jsx
import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
import {Svg, Rect, Path, Text} from 'react-native-svg';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg viewBox="0 0 36 28" width="100%" height="100%">
          <Rect fill="#EBECED" width="36" height="28" rx="4" />
          <Path
            fill="#999999"
            d="M5.8,4.5L4,8.7h1.2l0.3-0.8h2l0.3,0.8H9L7.2,4.5H5.8L5.8,4.5zM6.5,5.5L7.1,7H5.9L6.5,5.5L6.5,5.5z M9.1,8.7V4.5l1.7,0l1,2.7l1-2.7h1.7v4.2h-1.1V5.6l-1.1,3.1h-0.9l-1.1-3.1v3.1L9.1,8.7L9.1,8.7z M14.9,8.7V4.5h3.5v0.9h-2.4v0.7h2.3v0.9h-2.3v0.8h2.4v0.9H14.9L14.9,8.7z M18.5,8.7l1.7-2.1l-1.7-2.1h1.3l1,1.3l1-1.3h1.3l-1.7,2.1l1.7,2.1h-1.3l-1-1.3l-1,1.3L18.5,8.7L18.5,8.7z"
          />
          <Rect fill="#d3d3d3" x="4" y="10" width="6" height="5" rx="1" />
          <Text x="30" y="15" fontSize="3" textAnchor="middle">
            1234
          </Text>
          <Text x="18" y="19" fontSize="3" textAnchor="middle" fill="#838383">
            3333 122222 60000
          </Text>
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
});

```

**Comment by msand** [comment] 2019-10-04 14:22
<img width="1680" alt="Screen Shot 2019-10-04 at 17 21 56" src="https://user-images.githubusercontent.com/1131362/66215063-7d830980-e6cb-11e9-8bc5-bae3b6703f10.png">


```jsx
import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
import {Svg, Rect, Path} from 'react-native-svg';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Svg width="100%" height="100%" viewBox="0 0 50 50">
          <Rect
            x="12"
            y="12"
            width="26"
            height="26"
            fill="#fff"
            strokeWidth="2"
            rx="5"
            stroke="#000"
          />
          <Path
            fill="#fff"
            stroke="#000"
            strokeWidth="2"
            d="M17 12h16c2.8 0 5 2.2 5 5v16c0 2.8-2.2 5-5 5H17c-2.8 0-5-2.2-5-5V17c0-2.8 2.2-5 5-5z"
          />
          <Path
            d="M16,23l7,7,l12,-12"
            fill="none"
            stroke="#222"
            strokeWidth="3"
          />
        </Svg>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
});

```

**Comment by msand** [comment] 2019-10-04 14:23
This is with the latest version / develop branch, and react-native 0.61.1

**Comment by bogrees** [comment] 2019-10-04 14:26
Thanks @msand for verifying the latest versions.  Maybe this is a bug with RN < 0.6.0?  We are seeing the bug with 0.59.8.

**Comment by JackDavidson** [comment] 2019-10-06 04:33
I am also seeing the crashes from Rect on android. No errors are printed, the app just crashes. This was working for me until I ran 'npm install' again and upgraded something. Unfortunately I'm not certain whether it was react-native or react-native-svg updating that broke it.

@msand How do I get the 0.61.1 version of react-native?

Even when starting a brand-new project with expo, I see in yarn.lock that I am using:
version "0.59.8"

**Comment by JackDavidson** [comment] 2019-10-06 04:48
Also, here is a minimal reproduction of the issue:

https://github.com/JackDavidson/MinimalReactNativeSvgRectIssue

I simply created a new project with expo, installed react-native-svg, and copied an example from the read me in this repo. I have not tried with an android emulator, but it certainly crashes on my pixel 3 XL

**Comment by msand** [comment] 2019-10-06 07:43
@JackDavidson Try this:
```sh
react-native init MinimalReactNativeSvgRectIssue
cd MinimalReactNativeSvgRectIssue
yarn add react-native-svg
cd ios
pod install
cd ..
# Make changes to App.js
react-native run-ios
```

**Comment by msand** [comment] 2019-10-06 07:45
If you're using Expo, you should use the version of react-native-svg included with it, don't upgrade it / depend on in separately, there's no promises that the js code from one version will work with the native code of another

**Comment by msand** [comment] 2019-10-06 08:15
At least this seems to work just fine with the latest versions:

App.js
```jsx
import React from 'react';
import {StyleSheet, View} from 'react-native';
import Svg, {Circle, Rect} from 'react-native-svg';

export default function App() {
  return (
    <View style={styles.container}>
      <Svg height="50%" width="50%" viewBox="0 0 100 100">
        <Circle
          cx="50"
          cy="50"
          r="45"
          stroke="blue"
          strokeWidth="2.5"
          fill="green"
        />
        <Rect
          x="15"
          y="15"
          width="70"
          height="70"
          stroke="red"
          strokeWidth="2"
          fill="yellow"
        />
      </Svg>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

```

I would recommend using a plain react-native project, or the Bare workflow of Expo, or using Expokit (about to be deprecated): https://docs.expo.io/versions/v35.0.0/introduction/managed-vs-bare/

**Comment by JackDavidson** [comment] 2019-10-06 18:54
@msand you are correct - this does seem to work on android with version 0.61.2 of react-native. So is the only solution to either wait for an expo update or eject from expo then?

I really don't know what changed to make this break on me, I didn't do anything beyond re-run npm install.

**Comment by JackDavidson** [comment] 2019-10-06 21:27
@msand I didn't realize that react-native-svg was included with expo until you said it.

Turns out that if I lock react-native-svg dependency to the version that normally comes with expo, this works. That's version 9.9.2 for anyone else on this page that wants to know.

**Comment by bogrees** [comment] 2019-10-06 21:35
@JackDavidson, that makes sense now.  We had "~9.9.2" in our package.json, which is probably updating the library to something higher than "9.9.2" when running yarn, thus breaking it.  Ugh..  These library conflicts and incompatibilities can be maddening at times.

**Comment by anatula** [comment] 2019-10-07 13:40
@JackDavidson You are right, it is a problem with the version, I also thought it was "included" but one has to run _expo install react-native-svg_ [expo docs] (https://docs.expo.io/versions/latest/sdk/svg/). I was dealing with this issue for a few days now!. It was as @bogrees said ("**~**9.9.2"), I changed my package.json to this: `"react-native-svg": "9.9.2"` and I can run the example code without any issues.

**Comment by pkail** [comment] 2019-10-07 16:34
I finally got this to work using "9.9.2".  This was with a completely fresh install, so the incorrect version was put there by expo install react-native-svg.

**Comment by sirmong** [comment] 2019-10-16 10:13
Thanks! It works nice now with 9.9.2

**Comment by msand** [comment] 2019-10-19 20:29
Great, I'll close this now then.

**Closed by msand** 2019-10-19 20:29 UTC
Labels: bug, good first issue, help wanted, reproduction needed
