### ISSUE TITLE
Colors are not being displayed in Android 9.

### ISSUE THREAD

**Issue by RazaShehryar** [react-native-community/react-native-svg#1115] opened 2019-09-24 08:29 UTC
Hi

I am facing issues on Android 9. The SVG is being rendered on the device but.no colours are being shown in the output.

I am also attaching images for reference where the device where image is shown correctly is iOS while the other one is Android.

Library version: 9.9.4
Expo version: 35.0.0

![IMG_1312](https://user-images.githubusercontent.com/42263739/65494770-e2ba4c00-dece-11e9-9221-4bd317b2a121.JPG)
![IMG_1311](https://user-images.githubusercontent.com/42263739/65494771-e352e280-dece-11e9-8951-e8d79c8ac4d6.PNG)

**Comment by msand** [comment] 2019-09-24 11:08
Source?

**Comment by msand** [comment] 2019-09-25 15:27
Can you try v9.9.5?

**Comment by RazaShehryar** [comment] 2019-09-25 15:29
> Can you try v9.9.5?

Already tried. The issue is still there.

**Comment by msand** [comment] 2019-09-25 15:46
Can you post the full source, I'm unable to reproduce

**Comment by RazaShehryar** [comment] 2019-09-25 16:32
I am just including a simple Svguri from one of your examples listed in the documentations.

**Comment by msand** [comment] 2019-09-25 18:48
At least works fine in normal react-native, perhaps have to wait for expo to upgrade, although seems to work here: https://github.com/react-native-community/react-native-svg/issues/1088#issuecomment-535035972

**Comment by msand** [comment] 2019-09-25 18:48
https://github.com/expo/expo/pull/5770

**Comment by RazaShehryar** [comment] 2019-09-25 23:48
I tried again. Uninstalled it first with npm and then installed with Expo which upgraded it to v9.9.5. Also linked it with the library. Still the issue is there.
<img width="473" alt="Screenshot 2019-09-26 at 4 48 17 AM" src="https://user-images.githubusercontent.com/42263739/65647701-e22dcc80-e018-11e9-8e1a-529c809d21b2.png">

**Comment by msand** [comment] 2019-09-27 23:13
Anyway, this is fixed in the latest version, closing.

**Closed by msand** 2019-09-27 23:13 UTC
