### ISSUE TITLE
Error updating property 'strokeWidth' in RNSVGPath

### ISSUE THREAD

**Issue by iremlopsum** [react-native-community/react-native-svg#531] opened 2017-11-30 15:09 UTC
Just updated RN to `0.50.4` and `react-native-svg` to `6.0.1-rc.0` and getting the following error

```
Error while updating property 'strokeWidth' in shadow node of type: RNSVGPath

TypeError: expected dynamic type 'double', but had type 'string'
```

the error comes from

```
StaticTransformConfig transformConfig = new StaticTransformConfig();
transformConfig.mProperty = property;
transformConfig.mValue = transformConfigMap.getDouble("value");
```

Any ideas, what causing it? The most I've used `strokeWidth` is in the following form `strokeWidth="2"`

**Comment by dustinsavery** [comment] 2017-12-01 01:35
@iremlopsum haven't seen that before. Does this happen with `6.0.0`?

**Comment by skyout** [comment] 2017-12-01 19:49
@dustinsavery I can verify this happens on RN `0.50.4` and `react-native-svg 6.0.0` .

**Comment by dustinsavery** [comment] 2017-12-02 19:19
I just fired up a test project and tried the stroke width on a path: ```<Path d="M 40 60 A 10 10 0 0 0 60 60" stroke="black" strokeWidth="5" />```. This is using `react-native@0.50.4` and `react-native-svg@6.0.1-rc.0` Works just fine. Can you post your code or more details?

**Comment by HPieters** [comment] 2017-12-11 10:12
I have the same issue on Android only (iOS works fine) running react-native `0.50.4` and react-native-svg `6.0.1-rc1` with the following SVG:

```
<Svg height="35" width="35" viewBox="0 0 35 35">
<Path d="M25.30997,2.83092083 C22.9168541,1.47949378 20.1526344,0.708290378 17.2082904,0.708290378 C8.095592,0.708290378 0.708290378,8.095592 0.708290378,17.2082904 C0.708290378,26.3209888 8.095592,33.7082904 17.2082904,33.7082904 C26.3209888,33.7082904 33.7082904,26.3209888 33.7082904,17.2082904 C33.7082904,15.4394827 33.4299648,13.7356815 32.9147197,12.1382926" stroke="black" strokeWidth="2" fill="none" fillRule="evenodd" strokeLinecap="round"></Path>
</Svg>
```

**Comment by iremlopsum** [comment] 2017-12-11 10:17
I decided not to update `react-native-svg` version and kept it at `5.4.1`. This doesn't cause the error. Unfortunately I didn't have time to test on other versions of `react-native-svg` to see where and why the error happens :/

**Comment by macrozone** [comment] 2017-12-11 11:07
same issue here on android with 6.0.0. reverting back to 5.4.x

**Comment by dustinsavery** [comment] 2017-12-11 16:08
@hpieters that helps, I was testing on iOS. I’ll try my test project on android and see.

**Comment by robertobrogi** [comment] 2017-12-12 09:03
Hi, i have the same proble in adroid with 6.0.1-rc1 in Ios work fine....

**Comment by JulianKingman** [comment] 2018-01-01 21:32
I have the same problem with Android on 6.0.1-rc.1 using expo. I reverted to 5.4.1 and now have the same issue described here: https://github.com/FormidableLabs/victory-native/issues/168

**Comment by jwrubel** [comment] 2018-01-02 16:10
I'm also having a similar problem on `6.0.1-rc.1`. It looks like the iOS and android code handles conversion from a string property differently. I'm actually finding android is okay, but iOS fails because it cannot convert NSString to NSNumber in [this method](https://github.com/react-native-community/react-native-svg/blob/master/ios/Utils/RCTConvert%2BRNSVG.m#L41). strokeWidth is being added if not present and cast as a string [here](https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractStroke.js#L46). I can get the iOS version working by using `parseFloat(strokeWidth)` [here](https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractStroke.js#L56) but then the android version fails.  Downgrading to 5.5.1 brings up other errors with my particular SVG so that wasn't an option for me.

**Comment by msand** [comment] 2018-01-02 16:38
@jwrubel Are you sure you've rebuilt the native bundle? The stroke width should be a string, as it can have various units (em, %, px, pt etc.) https://github.com/react-native-community/react-native-svg/blob/e4269aed9f257e1829746dd53b923444a1c220c9/ios/RNSVGRenderable.m#L75-L82

**Comment by jwrubel** [comment] 2018-01-02 17:53
Admittedly I've only just integrated this library so I could be doing something wrong, but I've rebuilt the bundle a few times and I've built from xcode directly, and gotten the same error each time. I'll paste the SVG I'm using below but I've also tried with some of the samples from the example project and getting that same error when there are elements that accept strokeWidth. Like I said, it actually renders fine on iOS once you dismiss the error. But I've tried various combinations of setting the strokeWidth to various values with no luck.

```
<Svg width='39' height='62' viewBox='141 204 39 62'>
  <Defs>
    <LinearGradient x1='17.6779667%' y1='16.5597096%' x2='104.391096%' y2='16.5597099%' id='LinearGradient-1'>
      <Stop stopColor='#FFFFFF' stopOpacity='0' offset='0%'></Stop>
      <Stop stopColor='#FFFFFF' stopOpacity='0.3' offset='58.2838248%'></Stop>
      <Stop stopColor='#FFFFFF' stopOpacity='0' offset='100%'></Stop>
    </LinearGradient>
    <LinearGradient x1='50%' y1='0%' x2='50%' y2='100%' id='LinearGradient-2'>
      <Stop stopColor='#FFFFFF' stopOpacity='0.9' offset='0%'></Stop>
      <Stop stopColor='#FFFFFF' stopOpacity='0.15' offset='100%'></Stop>
    </LinearGradient>
    <LinearGradient x1='50%' y1='0%' x2='50%' y2='100%' id='LinearGradient-3'>
      <Stop stopColor='#FFFFFF' stopOpacity='0.2' offset='0%'></Stop>
      <Stop stopColor='#FFFFFF' stopOpacity='0.6' offset='100%'></Stop>
    </LinearGradient>
  </Defs>
  <G id='pint' stroke='none' strokeWidth='1' fill='none' fillRule='evenodd' transform='translate(141.000000, 204.000000)'>
    <Path d='M36.5259,0 L2.5259,0 C1.4219,0 0.4009,1.024 0.5259,2.172 L5.5259,60 C5.6489,61.129 6.4209,62 7.5259,62 L31.5259,62 C32.6309,62 33.3919,61.103 33.5259,60 L38.5099,2.125 C38.6329,1.008 37.6309,0 36.5259,0' id='glass' fill='#1F0000'></Path>
    <Path d='M3.608,3 L8.404,58.46 C8.431,58.766 8.686,59 8.993,59 L8.993,59 L30.059,59 C30.365,59 30.621,58.765 30.647,58.46 L30.647,58.46 L35.424,3 L3.608,3 Z' id='beer' fill='#D8E4E9' opacity='0.900000036'></Path>
    <Polygon id='foam' fill='#FFFDF0' points='3.608 3 4.214 10 34.821 10 35.424 3'></Polygon>
    <Path d='M3.608,3 L8.404,58.46 C8.431,58.766 8.686,59 8.993,59 L8.993,59 L30.059,59 C30.365,59 30.621,58.765 30.647,58.46 L30.647,58.46 L35.424,3 L3.608,3 Z' id='gradient' fill='url(#LinearGradient-1)' style='mix-blend-mode: overlay;' opacity='0.900000036'></Path>
    <Polygon id='accent' fill='url(#LinearGradient-2)' points='10.826 3 13.62 59 15.77 59 13.641 3'></Polygon>
    <Polygon id='accent' fill='url(#LinearGradient-3)' transform='translate(27.298000, 31.000000) scale(-1, 1) translate(-27.298000, -31.000000) ' points='24.826 3 27.62 59 29.77 59 27.641 3'></Polygon>
  </G>
</Svg>
```

**Comment by jwrubel** [comment] 2018-01-04 00:44
I don't know how but after adding and linking an unrelated project, this started working for me on iOS.  React-native development very often feels like trying to juggle sand.

**Comment by Softrabbit-de** [comment] 2018-01-27 16:42
Still have this error in 6.0.1 RC3 ... any news?

**Comment by msand** [comment] 2018-01-28 10:57
@Softrabbit-de Versions? Could you make a repo with a reproducible error?

**Comment by msand** [comment] 2018-01-28 11:03
These errors almost certainly result from upgrading react-native-svg, but not rebuilding the native ios code, while still running the updated js code.

**Comment by Softrabbit-de** [comment] 2018-01-28 18:08
I use the newest expo (v25) and have "react-native-svg": "6.0.1-rc.3" in combination with "victory-native": "0.16.6".

**Comment by msand** [comment] 2018-01-28 18:12
I think you have to eject from expo if you want to change the react-native-svg version, as otherwise you cannot change the native build. Expo has a prebuilt version, which seems to be pre v6

**Comment by Softrabbit-de** [comment] 2018-01-28 18:13
Thanks for that hint. Then I have to wait for them to update.

**Comment by msand** [comment] 2018-01-28 18:18
@brentvatne @dustinsavery would it be possible to get a new version into expo? any special requirements or tests that should pass?

**Comment by rori4** [comment] 2018-01-31 11:03
I had the same issue on Android with "react-native-svg": "6.0.1-rc.3" and "react-native" : "0.52.0"

**Comment by msand** [comment] 2018-01-31 11:08
@rori4 You probably forgot to rebuild your native bundle. Or are you using expo?

**Comment by spierr** [comment] 2018-02-01 21:18
Getting the same error using vitory-natiev and the next config:
"dependencies": {
    "expo": "^25.0.0",
    "firebase": "^4.9.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-svg": "^6.0.1-rc.3",
    "victory-native": "^0.16.6"
  }

**Comment by msand** [comment] 2018-02-02 08:27
@spierr Expo has a pre-built native version of react-native-svg, which is incompatible with the js code of the latest version. Either eject from Expo, or make a version upgrade request to the expo team, or downgrade to a compatible version. ping @brentvatne @dustinsavery

**Comment by msand** [comment] 2018-02-02 08:28
Seems we should add a Expo version compatibility table to the readme...

**Comment by spierr** [comment] 2018-02-02 19:56
You're totally right @msand. It would be nice to know which react-native-svg version is included in each release.

**Comment by msand** [comment] 2018-02-02 20:15
@spierr You can see it here: https://github.com/expo/expo-sdk/blob/c893c9c50a27f57370c2e4a18e98834c1012315c/package.json#L61

**Comment by msand** [comment] 2018-02-03 20:07
I've made a PR: https://github.com/expo/expo-sdk/pull/102

**Comment by msand** [comment] 2018-02-13 20:28
@ide I'll close this for now. But would be great to notify people here, if Expo updates the version. Not sure who has the rights/responsibilities to handle that, but thought you might be the right person.

**Closed by msand** 2018-02-13 20:28 UTC

**Comment by ishiestar** [comment] 2021-06-02 11:56
I have this issue with react-native-svg v12.1.1 and react-native v0.64.0, only on Android. I am not using expo. Is there any solution?
