### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by philographer** [react-native-community/react-native-svg#278] opened 2017-03-11 01:23 UTC
5.1.5 version has a memory leak issue.

I don't know why it occur.

Maybe VN: RNSVGSvgView (CALayer) does not free to go memory
(It continues to accumulate indefinitely)

but 4.6.1 version has no issue about memory leak. 

![image](https://cloud.githubusercontent.com/assets/13046348/23818976/f3ad8862-0643-11e7-92f6-429c66da49af.png)

**Comment by msageryd** [comment] 2017-11-17 10:08
This is a problem to me as well. I'm rendering SVG on top of a large image. When I leave the view I get back all allocated memory from the image (jpg), but the SVG allocation is not released.

Is this fixed in 6.0.0? I haven't had time to upgrade. If I knew this leak was fixed I'd upgrade asap.

I'm sorry, I don't have enough knowledge to give this a shot myself. Thank you for your great work.

**Comment by msageryd** [comment] 2017-11-17 10:40
I went ahead and upgraded to RN 0.50.3 and RN-SVG 6.0.0. No difference. Still leaking :(

**Comment by msageryd** [comment] 2017-12-12 13:21
Any ideas on what's going on? Should we implement 5+ in any other fashion than 4+ to work around the leak?

**Comment by dustinsavery** [comment] 2017-12-16 16:47
I haven’t had time to investigate this one. Do you have any additional details like platform? Also, if you happen to have the images and could drop them somewhere public so I could test, that would help.

**Comment by msageryd** [comment] 2017-12-17 17:16
@dustinsavery 
I have now isolated the problem in a new minimal app. The problem is the same in 5.5.1 and 6.0.1rc1.

Platform: iOS
RN: 0.51
Leaks in both simulator and on device

Steps to reproduce:
1. Created a bare-bone app with **create-react-native-app**
2. Eject the app to a regular react-native app
3. npm i react-native-svg --save
4. npm i
5. react-native link

This is the code I put directly in App.js:
    import React from 'react';
    import { StyleSheet, Text, View, Button } from 'react-native';
    import Svg, { Circle } from 'react-native-svg';

    export default class App extends React.Component {
      state = { counter: 0 };
      render() {
        return (
          <View>
            <View style={{ height: 50 }} />
            <Button
              title={'Re-render ' + this.state.counter}
              onPress={() => {
                this.setState({ counter: this.state.counter + 1 });
              }}
            />
            {this.state.counter % 2 === 0 && (
              <Svg height="1000" width="1000">
                <Circle
                  cx="200"
                  cy="150"
                  r={10 + this.state.counter}
                  strokeWidth="2.5"
                  stroke="#101010"
                  fill="red"
                />
              </Svg>
            )}
          </View>
        );
      }
    }

The key is to hide/reveal the SVG. If the same SVG is just re-rendered, there is no problem. But every time the SVG is rendered from scratch (i.e. it was not rendered previously), the memory footprint increases.

I made the SVG quite big to emphasise the problem.

Here is a screenshot from XCode Instruments after five re-renders. As you can see there SVG has five persistent objects totaling 343 MB.

![image](https://user-images.githubusercontent.com/4483085/34081909-7ed77616-e355-11e7-9890-43d62f23b193.png)

**Comment by dustinsavery** [comment] 2017-12-17 17:41
@msageryd that helps a ton, thanks for providing all those details!

**Comment by nikDemyankov** [comment] 2018-03-13 12:40
Hit the same issue. Seems like object is retained when you have structure like this:
```xml
<G>
  <G>
  </G>
</G>
```
or
```xml
<Defs>
  <G>
  </G>
</Defs>
```

Basically, if something has a child - you'll get a retained object on iOS.

**Comment by nikDemyankov** [comment] 2018-03-13 16:47
I found what causing retained objects for situations like:
```xml
<G>
  <G>
  </G>
</G>
```

It's `getSvgView` in `RNSVGNode.m`. It stores reference to the parent, parent has reference to the child, and as a result you get a retain cycle. At minimum it should be changed to:
```c
- (RNSVGSvgView *)getSvgView
{
    __kindof UIView *parent = self.superview;
    
    if ([parent class] == [RNSVGSvgView class]) {
        return parent;
    } else if ([parent isKindOfClass:[RNSVGNode class]]) {
        return [(RNSVGNode *)parent getSvgView];
    } else {
        RCTLogError(@"RNSVG: %@ should be descendant of a SvgViewShadow.", NSStringFromClass(self.class));
    }
    
    return nil;
}
```

But there is a similar issue with `RNSVGUse`. Maybe others as well, haven't check them yet. Will submit a PR as soon as possible.

Just wanted to share the findings in case someone is investigating this as well :)

**Comment by msand** [comment] 2018-03-13 18:28
Wonderful, thanks a lot for this, haven't had time to investigate this. Looking forward to your PR 👍

**Comment by nikDemyankov** [comment] 2018-03-14 16:27
@msand pr is up. Please, check it out :)

**Comment by msand** [comment] 2018-03-19 00:58
Released a new version, please help with testing to see if there are any remaining leaks!

**Comment by jamesreilly5** [comment] 2018-04-11 09:41
I tested this yesterday with my app which uses SVG images in FlatList with infinite scroll. The memery is consistent while profiling in Instruments so I would say this looks good to me.

**Comment by nikDemyankov** [comment] 2018-04-11 10:11
Same here: no more crashes on iOS because of the memory leaks.

**Comment by msand** [comment] 2018-12-09 01:48
Closing this as the issue seems to be fixed.

**Closed by msand** 2018-12-09 01:48 UTC
