### ISSUE TITLE
Mask Component

### ISSUE THREAD

**Issue by temphiza** [react-native-community/react-native-svg#273] opened 2017-03-03 21:22 UTC
Excellent work you done here, congrats!, we are working on a project using your lib and I'd like to know the status of the Mask component?

**Comment by ajonno** [comment] 2017-07-21 07:37
did you hear any update on this ? looking for same thing on a client project at mom.

**Comment by timperkins** [comment] 2017-08-03 15:33
A Mask component would be amazing! Is it still on the roadmap?

**Comment by raduflp** [comment] 2017-12-07 15:11
would love to see this implemented. 
upvote [this on canny](https://react-native.canny.io/feature-requests/p/maskedview-android-component)

in the meantime any suggestions on how would you go about drawing a semi-transparent rectangle with transparent circle inside using this library?

**Comment by catharp** [comment] 2017-12-07 20:26
@raduflp I found the `ClipPath` component to be a useful alternative to using mask in the alternative scenario (content visible _inside_ circle, transparent outside), but unfortunately I can't come up with a way to make that work for your specific case.  The best I can offer would be a hack like this:
```
  <Svg width="100" height="100">
    <Circle cx="50" cy="50" r="66" fill="rgb(0,0,0,0)" stroke="#E1E3E3" strokeWidth="50" />
  </Svg>
```

**Comment by smothers** [comment] 2018-01-01 22:22
a similar effect can be accomplished with ClipPath and a reversed stroke polygon or path 

```jsx
<Svg height="300" width="300">
  <Defs>
    <ClipPath id="clip">
      <Rect x="0" y="0" width="100%" height="100%" />
      <Polygon x="100" y="100" points="0,0 0,80 50,80, 50,0" /> {/* rect cutout */}
      <Path x="160" y="100" d="M0,20 l0,80 a20,20 0 0 0 20,20 l80,0 a20,20 0 0 0 20,-20 l0,-80 a20,20 0 0 0 -20,-20 l-80,0 a20,20 0 0 0 -20,20 Z" /> {/* round rect cutout */}
    </ClipPath>
  </Defs>
  <Rect
    x="0"
    y="0"
    width="100%"
    height="100%"
    fill="black"
    opacity="0.7"
    clipPath="url(#clip)"
  />
</Svg>
```

for a better description https://stackoverflow.com/a/11878784

**Comment by berpcor** [comment] 2018-07-20 22:57
Damn, man...
smothers, thanks for help but cut out that comment from code, or people, don't copy and paste it to your code. Killed almost an hour to find out what caused error on android emulator. This damn damn comment. How is that possible?..

**Comment by msand** [comment] 2018-09-11 22:59
@temphiza @ajonno @timperkins @raduflp @catharp @smothers @ma-pe @berpcor  @pruthvip @3rd-Eden @maxkomarychev @magicismight  I've implemented basic support for the Mask element here: https://github.com/react-native-community/react-native-svg/pull/757/commits/46307ecd2d2eb6849c0cb2465106201cb9901dda
Any help in testing is much appreciated! There might be some color space / gamma correction issue or something with iOS making the luminance to alpha calculation behave strange, haven't tested on any real devices yet.
yarn add react-native-svg@msand/react-native-svg#46307ec

**Comment by msand** [comment] 2018-09-12 00:01
Found the issue in iOS, now it should work quite alright.
`yarn add react-native-svg@msand/react-native-svg#b88cba8`

**Comment by msand** [comment] 2018-09-12 00:05
@smothers You're actually relying on buggy behaviour in your clip path workaround. You should have it as a single path element to use the fill-rule as you're now. I've made it spec conformant in my current work branch so that will be breaking when it gets released.

**Comment by msand** [comment] 2018-09-12 00:07
@smothers When building something with react-native-svg, I would recommend making sure your implementation works in the ever-green browsers as well (using e.g. the svgs library or plain svg files). If not, then it is likely to break once react-native-svg catches up with the standard.

**Comment by msand** [comment] 2018-09-15 16:38
v7.0.0 released

**Comment by Titozzz** [comment] 2018-09-17 00:52
Hello I tried using a mask but it crashes my app on android:

Svg used:
```
<Svg height="67" width="64" viewBox="0 0 64 67">
    <Defs>
      <Circle id="a" x="30" y="30" r="30" />
      <Circle id="d" x="8" y="8" r="8" />
    </Defs>
    <G fill="none" fillRule="evenodd">
      <G transform="translate(2 4.758)">
        <Mask id="b" fill="#fff">
          <Use href="#a"/>
        </Mask>
        <Path
          d="M15.684 46.433c3.108-3.244 7.802-4.866 14.083-4.866 6.28 0 10.974 1.622 14.082 4.866a8 8 0 0 1 2.224 5.535v10.788H13.46V51.968a8 8 0 0 1 2.224-5.535z"
          fill="#FC6563"
          stroke="#6F7592"
          strokeWidth="2"
          mask="#b"
        />
      </G>
    </G>
  </Svg>
```

Error:
```
 unknown:ReactNative  E  RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.
                         E  RNSVG: com.horcrux.svg.DefsShadowNode should be descendant of a SvgViewShadow.
                         E  RNSVG: com.horcrux.svg.GroupShadowNode should be descendant of a SvgViewShadow.
                         E  RNSVG: com.horcrux.svg.GroupShadowNode should be descendant of a SvgViewShadow.
          EGL_emulation  D  eglMakeCurrent: 0x9a8d35a0: ver 2 0 (tinfo 0x859c4630)
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: co.brigad.development, PID: 24131
                         E  java.lang.NumberFormatException: For input string: "undefined"
                         E      at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
                         E      at java.lang.Double.valueOf(Double.java:511)
                         E      at com.horcrux.svg.PropHelper.fromRelative(PropHelper.java:149)
                         E      at com.horcrux.svg.VirtualNode.relativeOnWidth(VirtualNode.java:324)
                         E      at com.horcrux.svg.RenderableShadowNode.render(RenderableShadowNode.java:260)
                         E      at com.horcrux.svg.GroupShadowNode$1.run(GroupShadowNode.java:87)
                         E      at com.horcrux.svg.VirtualNode.traverseChildren(VirtualNode.java:379)
                         E      at com.horcrux.svg.GroupShadowNode.drawGroup(GroupShadowNode.java:78)
                         E      at com.horcrux.svg.GroupShadowNode.draw(GroupShadowNode.java:69)
                         E      at com.horcrux.svg.RenderableShadowNode.render(RenderableShadowNode.java:301)
                         E      at com.horcrux.svg.GroupShadowNode$1.run(GroupShadowNode.java:87)
                         E      at com.horcrux.svg.VirtualNode.traverseChildren(VirtualNode.java:379)
                         E      at com.horcrux.svg.GroupShadowNode.drawGroup(GroupShadowNode.java:78)
                         E      at com.horcrux.svg.GroupShadowNode.draw(GroupShadowNode.java:69)
                         E      at com.horcrux.svg.RenderableShadowNode.render(RenderableShadowNode.java:301)
                         E      at com.horcrux.svg.SvgViewShadowNode$3.run(SvgViewShadowNode.java:220)
                         E      at com.horcrux.svg.SvgViewShadowNode.traverseChildren(SvgViewShadowNode.java:318)
                         E      at com.horcrux.svg.SvgViewShadowNode.drawChildren(SvgViewShadowNode.java:215)
                         E      at com.horcrux.svg.SvgViewShadowNode.drawOutput(SvgViewShadowNode.java:172)
                         E      at com.horcrux.svg.SvgView.onDraw(SvgView.java:100)
                         E      at android.view.View.draw(View.java:17071)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16053)
                         E      at android.view.View.draw(View.java:16837)
                         E      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                         E      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                         E      at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:698)
                         E      at android.view.View.draw(View.java:17074)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16053)
                         E      at android.view.View.draw(View.java:16837)
                         E      at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                         E      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                         E      at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:698)
                         E      at android.view.View.draw(View.java:17074)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16053)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)
                         E      at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)
                         E      at android.view.View.updateDisplayListIfDirty(View.java:16016)
                         E      at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                         E      at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                         E      at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                         E      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                         E      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                         E      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                         E      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                         E      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:619)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                         E      at android.os.Handler.handleCallback(Handler.java:751)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:154)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6077)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

Please let me know if you want more details :)
Using RNSVG 7.0.2

**Comment by msand** [comment] 2018-09-17 09:41
@Titozzz I think it might be because of no x,y,width,height attributes on the mask element, can you try adding something like this: 
      <Mask
        id="Mask"
        maskUnits="userSpaceOnUse"
        x="0"
        y="0"
        width="800"
        height="300"
      >
And perhaps move the Mask element inside the Defs element.

**Comment by Titozzz** [comment] 2018-09-17 09:43
I'll try and keep you updated. Have you seen https://github.com/react-native-community/react-native-svg/issues/781?

**Comment by msand** [comment] 2018-09-17 09:44
Yes, it doesn't have enough information to know what causes it. You error message gives more relevant info: 
                         E  java.lang.NumberFormatException: For input string: "undefined"
                         E      at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
                         E      at java.lang.Double.valueOf(Double.java:511)

**Comment by Titozzz** [comment] 2018-09-17 09:59
So: Crash when no x/y or no width/height

**Comment by Titozzz** [comment] 2018-09-18 15:30
@msand Do you need any more testing on my end ? I'd love to be able to use masks :)

**Comment by msand** [comment] 2018-09-19 09:49
Does it work correctly when you set x, y, w, h? I'm not sure what the defaults should be. Will need to read the spec more and test in some browsers. Might have time for it in the weekend in the best case.

**Comment by Titozzz** [comment] 2018-09-19 09:51
Well the app did not crash, but I did not find a size that would le t anything show through the mask, so it was displaying nothing :(

**Comment by jackmew** [comment] 2018-11-08 06:57
I use [svgr](https://github.com/smooth-code/svgr) to convert svg to react-native-svg component.

Everything is fine, except with <Mask>.

I also try to convert the svg myself. But there is still have problem about <Mask>

If there is <Mask>
1. [I need to add href manually](https://github.com/react-native-community/react-native-svg/issues/500).

**Comment by msand** [comment] 2018-11-08 16:46
@jackmew Can you try adding the x, y, width and height attributes to the Mask element? It needs to be specified explicitly for now it seems.

**Comment by jackmew** [comment] 2018-11-09 01:59
@msand I try to add x, y, width, height, but there is no effect. 

After adding href, AI.js can work. 
But show nothing relational about Mask element.

Mask & G use the same Path element.

![screen shot 2018-11-09 at 9 42 52 am](https://user-images.githubusercontent.com/6193983/48238374-c4a64300-e405-11e8-814a-4ec8e633cb0d.png)


Without Mask element.
I guess Mask is to hide the part of Blue Rect element.
The area of Mask is describe by Path element. 
If there is any blue Rect element cross over the Mask. It will be hided by Mask element.

![screen shot 2018-11-09 at 9 58 12 am](https://user-images.githubusercontent.com/6193983/48238445-020ad080-e406-11e8-858a-902c511a9760.png)


Trying to add x, y, width, and height attributes to the Mask element. But the value of attributes is no sense... Cause the size of Mask is described by Path element. Still not working.

![screen shot 2018-11-09 at 9 51 15 am](https://user-images.githubusercontent.com/6193983/48238230-2e721d00-e405-11e8-8437-7fa28cff0bf4.png)

Remove G element.

![screen shot 2018-11-09 at 9 53 48 am](https://user-images.githubusercontent.com/6193983/48238294-6d07d780-e405-11e8-9995-8312014a7cae.png)

Remove G element & Mask element.

![screen shot 2018-11-09 at 9 54 45 am](https://user-images.githubusercontent.com/6193983/48238314-86a91f00-e405-11e8-8b1d-4211bb202663.png)

**Comment by msand** [comment] 2018-12-09 01:36
@jackmew Open a new issue including a complete reproduction if you want progress on that issue. Will close this now as basic mask element support exists.

**Closed by msand** 2018-12-09 01:36 UTC

**Comment by david-laurentino** [comment] 2019-10-10 21:46
I'm trying implementing some svg filters for android. During process i realized that RenderableView apparently does not consider elements transformations while applying masks what seems to cause wrong renderization. I am not sure this is a problem or if the implementation is correct the way it is. The svg elements appears cutted and wrong positioned if i apply masks to elements with transformations. I made changes to java code that solve this problem for 'translate' transformations and then the svg is rendered as expected, but i fount no solution for scale transformations yet, although I understand what is happening. Now I'm focused on implementing the minimun of filters to produce shadows on elements with satisfatory results for now. Sorry about my english.

**Comment by msand** [comment] 2019-10-11 09:22
@david-laurentino Excellent! I would recommend testing the same content in the evergreen browsers, to ensure that they render the same, and that the syntax is supposed to behave as you expect to.
