### ISSUE TITLE
Error while updating property "d" of a view managed by RNSVGPath: V 9.8.1

### ISSUE THREAD

**Issue by Nahom-ab** [react-native-community/react-native-svg#1084] opened 2019-09-01 00:18 UTC
I saw that for others the recent update fixed this issue but it did not in my case. i downgraded to v 9.7.1.  to get it working.

### Code 
```
import React from 'react';
import {View, Text} from 'react-native';
import Svg, {Circle, Path, Rect} from 'react-native-svg';

const Test = () => {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'tomato',
      }}>
      <Svg height="100" width="100">
        <Path d="M 40 60 A 10 10 0 0 0 60 60" stroke="black" />
        <Rect x="0" y="0" width="100" height="100" fill="black" />
        <Circle cx="50" cy="50" r="30" fill="yellow" />
        <Circle cx="40" cy="40" r="4" fill="black" />
        <Circle cx="60" cy="40" r="4" fill="black" />
      </Svg>
    </View>
  );
};

export default Test;
```
## Error
```
Error while updating property "d" of a view managed by RNSVGPath: 

null

length 32; index=32
```
## Environment info

Phone: Android
react: 16.8.6
react-native: 0.60.5
Library version: 9.8.1
## Stack Trace
```
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5753)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=32; index=32
        at java.lang.String.indexAndLength(String.java:500)
        at java.lang.String.charAt(String.java:494)
        at com.horcrux.svg.PathParser.parse_number(PathParser.java:525)
        at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:497)
        at com.horcrux.svg.PathParser.parse(PathParser.java:152)
        at com.horcrux.svg.PathParser.parseData(PathParser.java:13)
        at com.horcrux.svg.PathView.setD(PathView.java:31)
        at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:395)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
        at android.view.Choreographer.doFrame(Choreographer.java:549) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
09-01 03:03:43.564 21910-21910/com.etunes E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' of a view managed by: RNSVGPath
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:549)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5753)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
        at android.view.Choreographer.doFrame(Choreographer.java:549) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
     Caused by: java.lang.StringIndexOutOfBoundsException: length=32; index=32
        at java.lang.String.indexAndLength(String.java:500)
        at java.lang.String.charAt(String.java:494)
        at com.horcrux.svg.PathParser.parse_number(PathParser.java:525)
        at com.horcrux.svg.PathParser.parse_list_number(PathParser.java:497)
        at com.horcrux.svg.PathParser.parse(PathParser.java:152)
        at com.horcrux.svg.PathParser.parseData(PathParser.java:13)
        at com.horcrux.svg.PathView.setD(PathView.java:31)
        at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:395)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:131) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:46) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:268) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
        at android.view.Choreographer.doFrame(Choreographer.java:549) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
09-01 03:03:43.684 21910-21910/com.etunes E/EmojiFactory_jni: Failed to load libemoji.so: dlopen failed: library "libemoji.so" not found
```

**Comment by msqar** [comment] 2019-09-01 02:31
This PR was created to fix this issue on latest version. Hope it can be merged quick

https://github.com/react-native-community/react-native-svg/pull/1085

**Comment by antoinerousseau** [comment] 2019-09-02 12:11
I'm using v9.8.3 (latest) and I'm getting this exact error with this path:
`<Path d="M24.581 7.098c.559-.345.559-.91 0-1.256L13.515.26c-.558-.345-1.472-.345-2.03 0L.42 5.842c-.559.345-.559.91 0 1.256l11.066 6.848c.558.345 1.472.345 2.03 0" />`

```
Error while updating property 'd' of a view managed by: RNSVGPath

null

length 153; index=153
```

**Comment by msqar** [comment] 2019-09-02 13:27
@antoinerousseau yes, seems it's not solved yet. I tested it too but went back to 9.7.1 which works 100%.

**Comment by antoinerousseau** [comment] 2019-09-02 13:35
Downgrading didn't solve it for me, but I put my SVG code into [SVGOMG](https://jakearchibald.github.io/svgomg/) and it gave me a different one that works... go figure!

```diff
<Svg width={25} height={25} viewBox="0 -1 25 24">
  <G fill={tintColor} fillRule="evenodd">
-   <Path d="M14.364 15.281c-.438.263-1 .408-1.58.408-.58 0-1.141-.145-1.58-.408l-7.15-4.29s-.645-.387-.645.49v4.284c0 2.257 4.197 4.69 9.375 4.69s9.375-2.433 9.375-4.69v-.302-4.224c0-.703-.459-.36-.459-.36l-7.336 4.402z" />
-   <Path d="M24.581 7.098c.559-.345.559-.91 0-1.256L13.515.26c-.558-.345-1.472-.345-2.03 0L.42 5.842c-.559.345-.559.91 0 1.256l11.066 6.848c.558.345 1.472.345 2.03 0" />
-   <Path d="M24.164 17.336V9.918s.005-.351-.226-.235c-.185.093-.64.321-.8.447-.184.145-.143.47-.143.47v6.736c0 .096-.09.141-.134.164-.42.223-.702.634-.702 1.105 0 .708.636 1.281 1.42 1.281.785 0 1.421-.573 1.421-1.281 0-.473-.284-.885-.706-1.107-.042-.022-.13-.066-.13-.162z" />
+   <Path d="M14.36 15.28c-.43.26-1 .4-1.58.4-.58 0-1.14-.14-1.58-.4L4.05 11s-.64-.39-.64.5v4.27c0 2.26 4.2 4.7 9.37 4.7s9.38-2.44 9.38-4.7v-4.52c0-.7-.46-.36-.46-.36l-7.34 4.4z" />
+   <Path d="M24.58 7.1c.56-.35.56-.91 0-1.26L13.52.26a2.12 2.12 0 0 0-2.03 0L.42 5.84c-.56.35-.56.91 0 1.26l11.07 6.85c.55.34 1.47.34 2.03 0M24.16 17.34V9.92s0-.35-.22-.24c-.19.1-.64.32-.8.45-.19.14-.14.47-.14.47v6.74c0 .1-.1.14-.14.16-.42.22-.7.63-.7 1.1 0 .71.63 1.29 1.42 1.29.78 0 1.42-.58 1.42-1.29 0-.47-.28-.88-.7-1.1-.05-.02-.14-.07-.14-.16z" />
  </G>
</Svg>
```

(the buggy line was the second path)

**Comment by msqar** [comment] 2019-09-02 13:36
@antoinerousseau u made it work with 9.8.3 or 9.7.1 ?

**Comment by antoinerousseau** [comment] 2019-09-02 13:40
latest (9.8.3)

**Comment by msqar** [comment] 2019-09-02 13:40
@antoinerousseau wow, nice man! i will give it a try today, then. Glad it worked.

**Comment by msand** [comment] 2019-09-02 16:33
Can you try with v9.8.4?

**Comment by rulo7** [comment] 2019-09-03 07:53
Hi, I had the same error than @antoinerousseau, but the new version, v9.8.4, seems to fix it. Thank you very much @msand :)

**Comment by msand** [comment] 2019-09-27 23:22
This seems to work fine in the latest version:
App.js
```jsx
import React from 'react';
import {View} from 'react-native';
import Svg, {Path} from 'react-native-svg';

const Test = () => {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'tomato',
      }}>
      <Svg height="100%" width="100%" viewBox="0 0 600 600">
        <Path
          fill="none"
          stroke={'black'}
          d="M240.77.05c-41.7 1.46-76.34 33.94-80.34 75.4a84 84 0 001.12 24s.13.9.56 2.62a83.71 83.71 0 005.64 16.58c8.39 19.85 27.8 53.06 71.35 89.19a7.29 7.29 0 009.29 0c43.55-36.09 63-69.3 71.39-89.23a79.7 79.7 0 005.64-16.61c.39-1.67.56-2.62.56-2.62A83.61 83.61 0 00240.77.05zm3 125.11a40.6 40.6 0 1140.67-40.6 40.62 40.62 0 01-40.7 40.6zm126.82 210.99l7-3.58s6.64-3.18 5.7-13-6.45-12.63-12-13.23c-3.83-.42-11.36-.53-15.64-.56-8.31-16.86-15.93-32.29-15.93-32.29s-4.55-8.07-11.62-12.93a37.33 37.33 0 00-21.1-6.91c-6.92-.05-78.13-.88-78.36-.66l-41.44-.25S176.92 251 165.23 258a43.53 43.53 0 00-16.86 18.78c-.35.65-6.69 13.08-14 27.44l-15.44-.13s-7.76.62-10.43 6.28-3.6 16.17 3.57 19.55c1.8.85 4.42 2.18 7.32 3.7-4.51 8.84-7.71 15.13-7.71 15.13s-5.28 12.88-5.37 24.41l-.72 85.56S104 476.53 121 476.67l24 .2s12.36.75 12.52-17.34l.07-8.58 172.51 1.45-.08 9.51s-1.34 16.32 12.87 16.44l28.62.25s10.25-.66 10.37-15.61l.74-87.41s-1.06-16.62-7.23-29.5c-1.01-2.16-2.7-5.64-4.8-9.93zm-255.1-13.89l1.82 1.71a2.91 2.91 0 01-1.82-1.71zm2.94 145.07a3.61 3.61 0 01-2-.84l3.1.84zm52.94-107a13.65 13.65 0 1113.76-13.54 13.65 13.65 0 01-13.76 13.56zm109.06 16.88a53.14 53.14 0 01-75.05-.63 7.11 7.11 0 0110.14-10 38.9 38.9 0 0055 .46 7.1 7.1 0 0110 10.13zm34.28-15.68A13.65 13.65 0 11328.48 348a13.65 13.65 0 01-13.77 13.55zM3 619.29c14 9.06 28.07 12.37 34.25 12.37 4.32 0 5.33-1.72 5.33-3.45 0-2-1.3-2.88-3.17-3.31-5-1.3-19.57-2.88-30.22-12.23C3.74 607.77 0 601 0 590.93c0-20.86 16.12-35.11 42.46-35.11 12.66 0 27.63 3.31 37.13 8.2v34.11c-13.53-6.76-26.2-9.21-31.52-9.21-4.18 0-5.33 1.58-5.33 3.17 0 2.15 1.59 3 3.31 3.59 4.32 1.3 18.71 3 28.93 11.08 7 5.76 10.51 13.1 10.51 22.46 0 20-16.12 34-43.47 34-13.09 0-28.78-3.17-39-8.49zm91.55-61.89H134c25 0 53.1 7.2 53.1 37 0 26.77-22.45 37.56-48.21 37.56h-1.44v29.64h-42.9zm44 48.07c7.34 0 10.79-3.89 10.79-8.78s-3.59-8.78-10.79-8.78h-1.15v17.56zm57.75-48.07h42.89v67.21h32.24v37H196.3zm86.35 0h42.89v104.2h-42.89zm87.21 35.12l-.14-.29H338.2V557.4h95.42l.14.29-37.56 70.52.14.29h34.83v33.1h-97.86l-.15-.29zm72.39-35.12h42.89v104.2h-42.89z"
        />
      </Svg>
    </View>
  );
};
const App = () => {
  return <Test />;
};

export default App;

```

**Closed by msand** 2019-09-27 23:22 UTC

**Comment by dmitry-mashkov** [comment] 2019-12-11 11:23
@msand the code above does **not** work for me with react-native-svg@9.13.6. Could you please share your package.json configuration ?

**Comment by msand** [comment] 2019-12-11 14:51
@dmitry-mashkov Can you try this?
https://github.com/react-native-community/react-native-svg#unexpected-behavior
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..

**Comment by dholbrook86** [comment] 2020-01-30 04:12
Also experiencing this issue in Rocket Chat
Android 10
Samsung Note 10+

**Comment by msand** [comment] 2020-01-31 17:47
Can you make a reproduction?

**Comment by dholbrook86** [comment] 2020-01-31 20:55
I'll try and get some more information when I dig into this bug next week. Thanks for the reply.

**Comment by ramilexe** [comment] 2020-03-03 10:55
any updates on this?

**Comment by ramilexe** [comment] 2020-03-03 12:21
updating to latest version `react-native-svg` helps.
this is the fix for root cause https://github.com/react-native-community/react-native-svg/commit/2d347347a32601ae680c4e7f91dc8846df52e65a#diff-12e8907b79d215169959eed6a0c198d7

**Comment by felipecruz91** [comment] 2020-03-09 20:32
Still having the same issue...

**Comment by eramudeep** [comment] 2020-03-19 22:01
having same problem on my mac machine.
works fine on Windows machine :(

**Comment by SuhairZain** [comment] 2020-04-17 15:17
> updating to latest version `react-native-svg` helps.
> this is the fix for root cause [2d34734#diff-12e8907b79d215169959eed6a0c198d7](https://github.com/react-native-community/react-native-svg/commit/2d347347a32601ae680c4e7f91dc8846df52e65a#diff-12e8907b79d215169959eed6a0c198d7)

This issue happened to us on an emulator an upgrading to the latest version (12.1.0) fixed it.

**Comment by shrey1728** [comment] 2020-11-04 19:15
facing similar issue but with the fill property of { Path } in react-native-svg in the latest version (12.1.0)

**Comment by MyRealFood** [comment] 2020-11-19 18:49
This issue is not fixed on 12.1.0, maybe related to 
https://github.com/react-native-svg/react-native-svg/issues/1491

**Comment by tmjordan** [comment] 2020-11-25 08:47
@MyRealFood Still having that issue with 12.1.0

**Comment by jarederaj** [comment] 2021-02-05 19:19
You can trigger this error when you attempt to graph a line that is not within the boundary of the SVG on iOS.

**Comment by aplinxy9plin** [comment] 2021-03-03 06:44
Same problem: "error while updating property "d" of a view managed by RNSVGPath"
Anyone can help me?

```jsx
<Svg preserveAspectRatio="none" width="95%" height="116">
  <Defs>
    <ClipPath id="svg-draw">
      <Path
        fillRule="evenodd"
        d={`M0 8C0 3.58172 3.58172 0 8 0H335C339.418 0 ${screenWidth} 3.58172 ${screenWidth} 8V50.2667C338.582 50.2667 1000 1000.729 1000 58C335 62.271 1000.582 65.7333 ${screenWidth} 65.7333V108C${screenWidth} 112.418 1000.418 116 335 116H7.99999C3.58172 116 0 112.418 0 108V67.6667C4.41828 67.6667 8 64.2043 8 59.9333C8 55.6623 4.41828 52.2 0 52.2V8Z`}
        fill="#fff"
      />
    </ClipPath>
  </Defs>
  <G clipPath="url(#svg-draw)" fillRule="nonzero" fill="#fff">
    <Rect width={screenWidth-16} height="116" />
    <Image href={ExampleImage} width={screenWidth/3} height="116" preserveAspectRatio="none" />
  </G>
</Svg>
```

**Comment by poojalivin** [comment] 2021-07-26 12:30
https://github.com/react-native-svg/react-native-svg/issues/1084#issuecomment-527200567

Tried different versions and reference.. Only this one gave me a solution

**Comment by felix-lambert** [comment] 2021-08-07 11:00
My version of react-native-svg is 12.1.0 should I go back to 9.8.4?

**Comment by felix-lambert** [comment] 2021-08-09 08:57
I tried to downgrade to 9.8.4 did'nt work I still have the crash

**Comment by LucasHimelfarb** [comment] 2021-09-23 19:26
> Traté de bajar de categoría a 9.8.4 no funcionó, todavía tengo el bloqueo

hi @felix-lambert could you find any solution?

**Comment by felix-lambert** [comment] 2021-09-24 13:23
No I had to uninstall react-native-svg because I had some random errors with some random devices and I did'nt know where it came from

**Comment by PrgrmmrOleg** [comment] 2021-10-01 12:42
An open question please. It still happens

**Comment by saaymeen** [comment] 2021-10-06 10:35
Having this error on Android with `react-native-svg@12.1.1`. Error does not happen on simulator (neither M1 nor Linux) and not on iPhone. Only on a real Android device for me.

**Comment by wmonecke** [comment] 2022-03-21 22:25
> Having this error on Android with `react-native-svg@12.1.1`. Error does not happen on simulator (neither M1 nor Linux) and not on iPhone. Only on a real Android device for me.

Same here. It's also hard to reproduce.

**Comment by AdhamMahmoud98** [comment] 2022-03-27 12:39
Any updates on this topic ?

**Comment by anmolpandeyy** [comment] 2022-07-04 06:31
Hi, I am still facing this issue in our production reported by firebase crashlytics

`Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' of a view managed by: RNSVGPath
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:143)`
       

Can you at least help in letting us know what are the possibilities that it will result in this crash? Maybe I can add some workaround in my code so as to prevent this from happening.

**Comment by scaralfred** [comment] 2022-07-06 19:56
Did anyone find a solution to this?
I'm still having this issue with versionn 12.3.0
Crashlytics is reporting thousands of crashes for my app.

**Comment by kesylo** [comment] 2022-10-28 02:14
PLease anyone found the issue ?

**Comment by vishnummenon** [comment] 2022-12-22 06:04
Does anyone know why this issue is closed? We are still getting many crash reports reported by firebase crashlytics.

**Comment by VashaMasha** [comment] 2023-04-13 16:24
In my case the problem was not in the library.
Please check your Svg components and parameters you pass to it.
I had this crash because I passed negative value in viewBox prop

**Comment by bzozoo** [comment] 2023-05-07 14:26
v12.3.0 is work for me.
