### ISSUE TITLE
viewBox problems

### ISSUE THREAD

**Issue by pkail** [react-native-community/react-native-svg#1238] opened 2020-01-04 15:13 UTC
# Bug

  Please provide a clear and concise description of what the bug is.
  Include screenshots if needed.
	<Svg width={w} height={h} viewBox="0, 0, 30, 50">
viewBox value is ignored and leads to an error: "Invalid `viewBox` prop:0, 0, 30, 50"
using viewBox="0 0 30 50" as described in the docs crashes the app.

Please test using the latest release of the library, as maybe said bug has been already fixed.
The latest version doesn't work with Expo at all.

## Environment info
"react-native-svg": "9.9.5",
"expo": "^35.0.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
Testing on iOS 13.1.2
  Run `react-native info` in your terminal and copy the results here. 
command not found

**Comment by msand** [comment] 2020-01-15 10:04
Can you make a complete reproduction?

**Comment by msand** [comment] 2020-01-15 10:09
At least the bare workflow seems to work just fine, snack seems to be working. And the next version of managed expo will probably have the latest version available. In general with the managed expo workflow, you should only use the same version as has been used to build the native code. There are no promises of native api backwards compatibility, only the public api is considered when deciding if it's a breaking change, that expo choose to bundle things things way is their choice and your choice to use, rather than a choice of mine.
`expo install react-native-svg` should install a compatible version for the sdk you're using, if i've understood correctly, so use that rather than npm or yarn directly.

**Comment by msand** [comment] 2020-03-08 10:04
No repro provided, closing.

**Closed by msand** 2020-03-08 10:04 UTC
Labels: reproduction needed
