### ISSUE TITLE
How can I solve the error 'ld: library not found for -lRNSVG-tvOS'?

### ISSUE THREAD

**Issue by chanhyeoni** [react-native-community/react-native-svg#375] opened 2017-06-18 19:23 UTC
I may make this post in a wrong place, but I will try. 

I would like to show a chart using react-native-pathjs-chart and victory-native, but somehow I get this following error every time I run `react-native run-ios`

![screen shot 2017-06-18 at 3 17 57 pm](https://user-images.githubusercontent.com/5059539/27263566-9da43300-5439-11e7-8dd2-ccaa0ac5b6e4.png)

According to the error file, it seems to me that there is an issue with linking the svg library. Or am I missing something here?

I use the following versions
react-native-svg: 5.2.0
react-native: 0.45.1
react:16.0.0-alpha.12

And my index.ios.js code looks like this.

```
import React, { Component } from 'react';
import { AppRegistry, Text, StyleSheet, View, Button } from 'react-native'
import { StackNavigator} from 'react-navigation';
import { Radar } from 'react-native-pathjs-charts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f7f7f7',
  },
});

export default class Prototype1 extends Component {

  // static navigationOptions = ({ navigation }) => ({
  //   title: `Radar - Basic`,
  // });

  render() {

    let data = [{
      "speed": 74,
      "balance": 29,
      "explosives": 40,
      "energy": 40,
      "flexibility": 30,
      "agility": 25,
      "endurance": 44
    }]

    let options = {
      width: 290,
      height: 290,
      margin: {
        top: 20,
        left: 20,
        right: 30,
        bottom: 20
      },
      r: 150,
      max: 100,
      fill: "#2980B9",
      stroke: "#2980B9",
      animate: {
        type: 'oneByOne',
        duration: 200
      },
      label: {
        fontFamily: 'Arial',
        fontSize: 14,
        fontWeight: true,
        fill: '#34495E'
      }
    }

    return (
      <View style={styles.container}>
        <Radar data={data} options={options} />
      </View>
    );
  }
  }
}


AppRegistry.registerComponent('Prototype1', () => Prototype1);
```

Please let me know if I should look at something else other than the linking

**Comment by ronal2do** [comment] 2017-06-22 02:04
+ 1

**Comment by hellomaya** [comment] 2017-08-04 15:28
Temporary solution, use Xcode to open the project, and then remove this lib at Linked Framework and Library section.

**Comment by magicismight** [comment] 2017-08-09 02:17
Fixed in latest version

**Closed by magicismight** 2017-08-09 02:17 UTC

**Comment by msand** [comment] 2018-01-17 20:27
This is caused by a bug in react-native link, fix will be merged soon: https://github.com/facebook/react-native/issues/13783
