### ISSUE TITLE
Build fails with: library not found for -lRNSVG-tvOS

### ISSUE THREAD

**Issue by jd20** [react-native-community/react-native-svg#544] opened 2017-12-15 04:52 UTC
This looks like the same issue as #387, and was fixed in 5.3.1, but I'm seeing this build error even with newer versions of react-native-svg. Repo steps:

1. Create a new project with `react-native init`
2. Run `yarn add react-native-svg`
3. Run `react-native link react-native-svg`
4. Run `react-native run-ios` and observe the build error: `ld: library not found for -lRNSVG-tvOS`

My dependency versions from package.json are:

```
  "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-svg": "^6.0.1-rc.1"
  },
```

If I open the XCode project and remove the RNSVG-tvOS.a library under "Recovered References" folder, then build succeeds.

**Comment by dustinsavery** [comment] 2017-12-18 21:07
@jd20 did you run `react-native link react-native-svg`?

**Comment by jd20** [comment] 2017-12-19 00:09
Sorry, forgot to include that in the instructions above, yes I ran react-native link after adding the package. Actually, pretty sure it's the link command command which is adding the problematic RNSVG-tvOS.a reference to the XCode project.

**Comment by aaronklaser** [comment] 2017-12-27 17:23
+1 ... I am also having this issue -_-

**Comment by dhamdani666** [comment] 2017-12-28 09:24
i think not support with react-native version 0.51.0

**Comment by jd20** [comment] 2017-12-29 08:23
The library seems to work fine with 0.51.0, just have to remove the RNSVG-tvOS.a reference. Maybe it'd make sense to make a note of this in the installation instructions, unless a fix is coming soon.

**Comment by savovs** [comment] 2018-01-04 03:17
Noob here, @jd20 how do you remove the reference?

**Comment by jd20** [comment] 2018-01-04 03:23
Open the XCode project form your project's ios folder, hit the Project Navigator button top left, and look for the folder "Recovered References". Select the item RNSVG-tvOS.a, and hit delete, it will be removed from the project. Then you can try to build again (either Cmd+B from XCode or `react-native run-ios` from command line), you might need to do a Build > Clean first if it's still not working (Cmd+K in XCode).

I don't have an exact screenshot, but here's something close:

<img width="307" alt="screen shot 2018-01-03 at 7 19 51 pm" src="https://user-images.githubusercontent.com/17896438/34549163-7efd8a7c-f0bb-11e7-99aa-1060956c9e83.png">

If you don't see the item under Recovered References, make sure you ran `react-native link`, that's what creates it.

**Comment by savovs** [comment] 2018-01-04 03:35
Removing it from here did the trick 
![screen shot 2018-01-04 at 3 34 59 am](https://user-images.githubusercontent.com/1226564/34549401-525e2068-f100-11e7-9e1d-5e911a5cb5a9.png)

**Comment by msand** [comment] 2018-01-17 20:27
This is caused by a bug in react-native link, fix will be merged soon: https://github.com/facebook/react-native/issues/13783

**Closed** 2018-02-13 20:17 UTC

**Comment by AndrewJDick** [comment] 2018-07-31 08:18
@savovs 👋
