### ISSUE TITLE
Resize path

### ISSUE THREAD

**Issue by doublex** [react-native-community/react-native-svg#480] opened 2017-10-13 20:22 UTC
Example (a simple dot):
````
<Svg style={{width: 110, height: 110}} viewbox="0 0 22 22">
  <Path d="M11,0C4.926,0,0,4.926,0,11s4.926,11,11,11s11-4.926,11-11S17.074,0,11,0z" />
</Svg>
````

Same:
````
<Svg width={110} height={110} viewbox="0 0 22 22">
  <Path d="M11,0C4.926,0,0,4.926,0,11s4.926,11,11,11s11-4.926,11-11S17.074,0,11,0z" />
</Svg>
````

Only the canvas got resized - not the dot.

**Comment by chocky335** [comment] 2017-12-04 14:00
the same issue with other paths, actual just for android

**Comment by EskelCz** [comment] 2018-01-15 19:05
Just to make sure, the viewbox dimensions should be the original dimensions of the shape.

**Comment by chocky335** [comment] 2018-01-15 23:25
@EskelCz What do you mean? as I know viewbox dimensions are the same for android and iOS)

**Comment by mnicolls** [comment] 2018-01-16 15:53
+1 Expecting Path to scale within Svg "canvas", but it is not.  Tried setting width and height on Path to no avail.  I've been able to resize it using transform={{scale:'0.5, 0.5'}}, but that seems like a work around.

**Comment by EskelCz** [comment] 2018-01-16 19:25
@mnicolls just set the viewbox to the original size of the shape, then the resize will work with just width and height

**Comment by mnicolls** [comment] 2018-01-16 19:30
Thanks EskelCz, great point.  Ideally though, I would prefer to not know the dimensions of the SVG at all.  In short, I don't care if it is 500x500 or 50x50, I just want it to render at 24x24.  Or better yet, render at 100% to fit within the available space of a button container, etc. 

If this isn't possible, is there some way to get the dimensions of the path programmatically?  Then I could resize the image using the onLayout event, e.g. scale = this.width / 24

**Comment by EskelCz** [comment] 2018-01-16 22:25
@mnicolls I understand, but I guess you have to conform to how it works. The numbers in the vector path are coordinates in a cartesian plane and it seems like the viewBox is just a definition of a boundry box, that lets the svg know how large your shape is. It could be easily calculated from the path numbers (just simple min-max lookup) but they let it up to you to draw the 'boundries' of the data.

**Comment by mnicolls** [comment] 2018-01-16 23:17
I hear you.  So if the viewBox is a “boundary box”, are child components supposed to observe and adhere the boundaries? Is it “okay” that a path be rendered outside of the viewBox?

On Jan 16, 2018, at 4:26 PM, David Spohr <notifications@github.com<mailto:notifications@github.com>> wrote:


@mnicolls<https://github.com/mnicolls> I understand, but I guess you have to conform to how it works. The numbers in the vector path are coordinates in a cartesian plane and it seems like the viewBox is just a definition of a boundry box, that lets the svg know how large your shape is. It could be easily calculated from the path numbers (just simple min-max lookup) but they let it up to you to draw the 'boundries' of the data.

**Comment by EskelCz** [comment] 2018-01-16 23:31
@mnicolls  Technically it's okay to be outside but when you change the width and height to differ from viewBox, everything outside it will get cropped. That's probably not what you want in most cases. So you want to know the dimensions of the shape.

**Comment by mnicolls** [comment] 2018-01-17 01:23
It makes sense to default to cropping, that’s probably more logical than assuming it should automatically scale (which comes with other baggage... scale to which dimension? stretch to fit?), my preference would be to have the path implement a dimension (other than a percentage-based scale), yet maintain aspect ratio if only one dimension were specified — like the trusty <img> html element.  But, if that is not supported at this time I will hard-code scale based on a percentage of the known size of the SVG.

Thanks for the discussion!

On Jan 16, 2018, at 17:31, David Spohr <notifications@github.com<mailto:notifications@github.com>> wrote:


@mnicolls<https://github.com/mnicolls> Technically it's okay to be outside but when you change the width and height to differ from viewBox, everything outside it will get cropped. That's probably not what you want in most cases. So you want to know the dimensions of the shape.

**Comment by DaKaZ** [comment] 2018-02-05 23:08
I too ran into this issue and it appears to only be on Android.  We use viewBox and it just doesn't work.  The paths are NOT re-rendered when width/height props are updated.  I added a console.log in there and I do see the render method being called with then new props, but either React or the android native SVG library refuses to re-render the component.

Here is what it looked like before my hacky fix which android would crop the image:
<img width="994" alt="screen shot 2018-02-05 at 3 25 02 pm" src="https://user-images.githubusercontent.com/895892/35833394-439058f6-0a8e-11e8-964f-27ec7122e6c7.png">
and then after my fix:
<img width="991" alt="screen shot 2018-02-05 at 4 04 58 pm" src="https://user-images.githubusercontent.com/895892/35833407-5a4c9afa-0a8e-11e8-93aa-531fe2efd590.png">

So how did I do it, by tracking size of the component and using a scale transform on android like this:
```
import React from 'react';
import { View, Platform } from 'react-native';
import Svg, { Path, G } from 'svgs';

class FodLogo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      size: props.size
    };
  }

  render() {
    const androidProps =
      Platform.OS === 'android' ? { scale: this.props.size / this.state.size } : null;
    const otherProps =
      Platform.OS === 'android' ?
        { width: this.state.size, height: this.state.size } :
        { width: this.props.size, height: this.props.size };
    return (
      <View style={{ width: this.props.size, height: this.props.size }}>
        <Svg {...otherProps} viewBox="0 0 95 95" title="Field Operations Directorate Logo">
          <G {...androidProps}>
            <Path
              d="M67,35 L75,8.8 C67.3,3.4 58,0.2 47.8,0.2 C40,0.2 32.6,2.1 26.1,5.5 L67,35 Z"
              fill="#005288"
            />
            <Path
              d="M80.8,13.6 L66,62 L92.7,61.9 C94.2,57.3 95,52.4 95,47.3 C95,34.1 89.6,22.1 80.8,13.6 Z"
              fill="#C0C2C4"
            />
            <Path
              d="M42.1,24.9 L21,8.6 C8.8,17.1 0.7,31.3 0.7,47.3 C0.7,50.4 1,53.3 1.6,56.2 L42.1,24.9 Z"
              fill="#669900"
            />
            <Path
              d="M41,69 L47.8,94.5 C47.8,94.5 47.8,94.5 47.9,94.5 C66.1,94.5 81.9,84.2 89.8,69 L41,69 Z"
              fill="#007BB1"
            />
            <Path d="M26,46 L3.5,63.3 C9.4,79.6 24,91.7 41.7,94.1 L26,46 Z" fill="#CC3333" />
          </G>
        </Svg>
      </View>
    );
  }
}

export default FodLogo;
```

**Comment by msand** [comment] 2018-02-05 23:22
I think this might be because of how the width and height props are handled. They're not sent as props over the bridge to the native side of the svg root component, they're given as dimensions to the react-native view/stylesheet yoga handling layer. I guess they're not causing any invalidation on the android side and thus no re-rendering. I'm currently looking into adding support for nested svgs and will probably have a fix for this issue at the same time because of related changes.

**Comment by DaKaZ** [comment] 2018-02-06 20:34
@msand well done!  I can confirm that the height/width is now successfully re-rendered on Android with your branch for NestedSvg

**Comment by axelnormand** [comment] 2018-02-14 14:16
Thanks @DaKaZ your scale fix on "G" worked for me within expo

**Comment by msand** [comment] 2018-02-14 14:34
@axelnormand That is correct. Alternatively, you can put e.g. a text element with opacity 0, and put a counter inside which you increment, or some other arbitrary property which causes an invalidation of the tree.

**Comment by ferpalma21** [comment] 2018-04-28 19:57
impossible to resize in ios

`import React from "react";
import Svg, { Defs, G, Path } from "react-native-svg";

const Building = props => (
<Svg width={props.width || 2933} height={props.height || 2933} viewBox="0 0 2933 2933"><Defs ></Defs>
  <G id="__x0023_Layer_x0020_1"><G id="_261566584"><Path class="fil0" d="M1867 1467h-800v1333h800V1467zm-57-133h-687l343-343 343 343zM667 2534H534v267h133v-267zm267-267H267v533h133v-400h400v400h133v-533zm-610-133l267-267h343v267H324zm2143 267h-133v400h133v-400zm333-2267h-800v2667h200v-533h400v533h200V134zM1067 2934h1867V1H1867v1200l-400-400-533 533v400H534L1 2267h133v667h933z"></Path>
  <Path class="fil1" d="M2600 1600h-133v-133h133zM2600 800h-133V667h133zM2600 1333h-133v-133h133zM2600 533h-133V400h133zM2600 1067h-133V933h133zM2333 1600h-133v-133h133zM2333 800h-133V667h133zM2333 1333h-133v-133h133zM2333 533h-133V400h133zM2333 1067h-133V933h133zM2600 1867h-133v-134h133zM2333 1867h-133v-134h133z"></Path>
  <Path class="fil0" d="M1200 2133h533v400h-533v-400zm0-533h533v400h-533v-400zm133 667h267v133h-267v-133zm0-533h267v133h-267v-133z"></Path></G></G></Svg>
);

export default Building;
`
any fixes?

**Comment by ferpalma21** [comment] 2018-04-28 20:15
impossible to resize in ios

SVG.js Component
`
import React from "react";
import Svg, { Defs, G, Path } from "react-native-svg";

const Building = props => (
<Svg width={props.width || 2933} height={props.height || 2933} viewBox="0 0 2933 2933"><Defs ></Defs>
  <G id="__x0023_Layer_x0020_1"><G id="_261566584"><Path class="fil0" d="M1867 1467h-800v1333h800V1467zm-57-133h-687l343-343 343 343zM667 2534H534v267h133v-267zm267-267H267v533h133v-400h400v400h133v-533zm-610-133l267-267h343v267H324zm2143 267h-133v400h133v-400zm333-2267h-800v2667h200v-533h400v533h200V134zM1067 2934h1867V1H1867v1200l-400-400-533 533v400H534L1 2267h133v667h933z"></Path>
  <Path class="fil1" d="M2600 1600h-133v-133h133zM2600 800h-133V667h133zM2600 1333h-133v-133h133zM2600 533h-133V400h133zM2600 1067h-133V933h133zM2333 1600h-133v-133h133zM2333 800h-133V667h133zM2333 1333h-133v-133h133zM2333 533h-133V400h133zM2333 1067h-133V933h133zM2600 1867h-133v-134h133zM2333 1867h-133v-134h133z"></Path>
  <Path class="fil0" d="M1200 2133h533v400h-533v-400zm0-533h533v400h-533v-400zm133 667h267v133h-267v-133zm0-533h267v133h-267v-133z"></Path></G></G></Svg>
);

export default Building;
`

I tried several things in the view like nesting it in another view, or passing it directly as props in style, but nothing is working. 

`
import React, { Component } from 'react';
import {  AppRegistry, StyleSheet, Text, View, Image } from 'react-native';
import Swiper from 'react-native-swiper';
import IcoBuilding from './svg/Building';


import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

export default class SwiperScreen extends Component {
  constructor(props){
    super(props);
    firstSlide={
      title: 'ALKSDJOISGDFH,
      subtitle: 'lipsum lapsu lasdaasd asfdiohsagfosiang aDSKJ.'
    },
    secondSlide={
      title: 'KJDIOSAHDF kansdfionf,
      subtitle: 'Don\'ASFJPOOISDGHFJ A SFASDKOP iaoshfsdnfalskfndjkasdfbn adskjf asdjasoid.'
    },
    thirdSlide={
      title: 'añslfjoihjgf kalsfkaoshf,
      subtitle: 'AOIJFS KAJDSF AOPSJD asodfjkodmf 012I3EOPJDIOAKMKSAMkmc as0d8i0ojkpDS '
    }
  }
  render(){
    return (
      <Swiper style={styles.wrapper} >
        <View style={styles.slide1}>
        <View style={{width: 200, height:200, backgroundColor:'#000', opacity:.5}}>
          <IcoBuilding style={{opacity:1, backgroundColor:'#000'}}/>
          </View>
          <Text style={styles.title}>{firstSlide.title}</Text>
          <Text style={styles.subtitle}>{firstSlide.subtitle}</Text>
        </View>
        <View style={styles.slide2}>

          <Text style={styles.title}>{secondSlide.title}</Text>
          <Text style={styles.subtitle}>{secondSlide.subtitle}</Text>
        </View>
        <View style={styles.slide3}>

          <Text style={styles.title}>{thirdSlide.title}</Text>
          <Text style={styles.subtitle}>{thirdSlide.subtitle}</Text>
        </View>
      </Swiper>
    );
  }
}

const styles = StyleSheet.create({
  wrapper: {
  },
  ico: {
    width: 250,
    height: 250
  },
  slide1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'yellow',
  },
  slide2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'blue',
  },
  slide3: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
  title: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
  },
  subtitle:{
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 20,
    margin: 10
  },
  stretch: {
    width: 200,
    height: 100
  }
})

`

I I already linked and downgrade the version of my react-native-svg but didn't work either

`
{
  "name": "prework",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.4.2",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-app-intro": "https://github.com/merryjs/react-native-app-intro",
    "react-native-elements": "^0.19.1",
    "react-native-svg": "^6.1.3",
    "react-native-svg-icon": "^0.8.1",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

`

**Comment by msand** [comment] 2018-09-25 13:30
@ferpalma21 I think the issue is that you're drawing black on a black background, so it's all black. Try this with the latest version:

```jsx
import React, { Component } from 'react';
import { View } from 'react-native';
import { Svg, Path } from 'react-native-svg';

const Building = ({ width = '100%', height = '100%' }) => (
  <Svg width={width} height={height} viewBox="0 0 2933 2933">
    <Path d="M1867 1467h-800v1333h800V1467zm-57-133h-687l343-343 343 343zM667 2534H534v267h133v-267zm267-267H267v533h133v-400h400v400h133v-533zm-610-133l267-267h343v267H324zm2143 267h-133v400h133v-400zm333-2267h-800v2667h200v-533h400v533h200V134zM1067 2934h1867V1H1867v1200l-400-400-533 533v400H534L1 2267h133v667h933z" />
    <Path d="M2600 1600h-133v-133h133zM2600 800h-133V667h133zM2600 1333h-133v-133h133zM2600 533h-133V400h133zM2600 1067h-133V933h133zM2333 1600h-133v-133h133zM2333 800h-133V667h133zM2333 1333h-133v-133h133zM2333 533h-133V400h133zM2333 1067h-133V933h133zM2600 1867h-133v-134h133zM2333 1867h-133v-134h133z" />
    <Path d="M1200 2133h533v400h-533v-400zm0-533h533v400h-533v-400zm133 667h267v133h-267v-133zm0-533h267v133h-267v-133z" />
  </Svg>
);

export default class App extends Component {
  render() {
    return (
      <View style={{ flex: 1, padding: 20 }}>
        <Building />
      </View>
    );
  }
}
```

<img width="1420" alt="screen shot 2018-09-25 at 16 27 21" src="https://user-images.githubusercontent.com/1131362/46017430-1dcd4800-c0e0-11e8-8a39-be2987dc0d36.png">

**Comment by msand** [comment] 2018-12-09 01:40
Closing this as viewbox works correctly.

**Closed by msand** 2018-12-09 01:40 UTC
