### ISSUE TITLE
Intermittent failure to render on iOS 11

### ISSUE THREAD

**Issue by rh389** [react-native-community/react-native-svg#516] opened 2017-11-16 16:24 UTC
I'm still investigating this and will add more here as I discover it, but I'm seeing that several (but not all) SVGs in my app intermittently (but not always) fail to render. Is anyone else seeing this?

According to the inspector, the element is there and has its proper dimensions as normal, but at least one element is completely invisible.

In my case, the elements in question are all `Circle`s or `Rect`s with gradient fills that are overlayed by something else. In one case, I have several shapes within one `<Svg>` component, and only one of those shapes ( a `Circle`) is intermittent, the rest work (inlcuding another `Circle`) never fail.

**Comment by MrLoh** [comment] 2017-11-25 13:41
I’m experiencing something similar. Sometimes my SVGs don’t render. They all contain just one path though and not circles. I didn’t associate it with iOS11 so far, but it could be. Also happens much more often in the simulator.

**Comment by rh389** [comment] 2017-11-25 16:50
It does seem to vary between devices, although I've seen it happen at least once on everything (iPad Pro, iPhone 6 simulator, iPhone SE) except an iPhone 6 still running iOS 10, hence the iOS 11 association.

I haven't been able to make any headway on it unfortunately, there are no errors or warnings and no way of programmatically detecting the problem I've been able to find. For now I've resorted to rendering a fallback view behind my SVG, which shows through only when the SVG fails.

Are you also using wix navigation by any chance?

**Comment by MrLoh** [comment] 2017-11-25 16:51
Yep also using React native navigation

**Comment by rh389** [comment] 2017-11-25 16:58
Interesting. Could be a coincidence, I've just suspected it might be related because navigation transitions seem to cause the svgs to disappear/reappear sometimes, whereas I haven't noticed that with any other re-renderings.

**Comment by dustinsavery** [comment] 2017-11-26 23:52
As noted in #526, it appears it is not isolated to iOS, Android is having a similar issue. The common item across all of these occurrences so far is react-native-navigation. Can you all post the versions you're using? I want to try and narrow down the search.

**Comment by rh389** [comment] 2017-11-27 00:00
Thanks for investigating, although the OP in https://github.com/react-native-community/react-native-svg/issues/526 may actually be using `react-navigation` rather than `react-native-navigation`? 

I was using:

react-native-svg 5.4.1
react-native 0.49.3
react-native-navigation 1.1.273

I've recently updated to RNSVG 6.0.0 and RN 0.50.1 - haven't seen the issue yet but it's too early to say.

**Comment by MrLoh** [comment] 2017-11-27 10:42
react-native: 0.47.2
react-native-navigation: ^1.1.235
react-native-svg: ^5.4.1

**Comment by MrLoh** [comment] 2017-11-27 13:32
I just updated to 
react-native-navigation: 1.1.295
react-native-svg: 6.0.0

and the issue is still there

**Comment by dustinsavery** [comment] 2017-11-27 18:55
So it appears the common point is `react-native-navigation@1.1.x` so far

**Comment by MrLoh** [comment] 2017-11-27 19:20
And iOS11, there’s no indication so far that #526 is using React native navigation

**Comment by MrLoh** [comment] 2017-12-04 20:13
I found a workaround, my app reliably didn’t render any SVGs after pushing a screen anymore, which made it unusable. 

I‘m now simply triggering a rerender of the SVG path, after it loaded by setting a new color value in a 0 timeout in componentDidMount.

**Comment by rh389** [comment] 2018-04-03 14:47
https://github.com/react-native-community/react-native-svg/commit/ca9855b1cd3b711d046a05caa5608695a031b1f6 looks promising as a fix. I'll be trying it out over the next few weeks

**Comment by alburdette619** [comment] 2018-11-28 17:17
Been quite a while and I'm seeing this with my paths.  I am also using react-native-navigation now at `^2.18.2`.  Specifically I'm using react-native-svg-charts and have implemented muti line charts.  It only seems to affect those.  You can see the PR file in question here: https://github.com/JesperLekland/react-native-svg-charts/pull/240/files

Specifically `/src/chart/chart-grouped.js`

**Comment by MrLoh** [comment] 2018-11-29 14:19
This doesn't seem to happen for me anymore. But much in my setup has changed.

• iOS 12.1
• react-native: 0.55.4
• react-navigation: 2.2.5
• react-native-svg: 6.2.1

**Comment by msand** [comment] 2018-12-09 01:42
Closing this until a reproduction is provided.

**Closed by msand** 2018-12-09 01:42 UTC
