### ISSUE TITLE
:app:dexDebug

### ISSUE THREAD

**Issue by julesmoretti** [react-native-community/react-native-svg#174] opened 2016-11-09 17:54 UTC
Hello there:

After going through the following: http://facebook.github.io/react-native/docs/getting-started.html

And then added react-native-svg to the mix I get the following error:

```
:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 35.916 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

[jmoretti:~/Sync/Google Drive/kikiPoc-jm]$ 
```

Any ideas how I could go about resolving this?

The regular project runs fine through the android emulator, but as soon as I try adding this module it gives me the above error.

here is my JSON file

```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.36.1",
    "react-native-svg": "^4.3.2"
  },
  "jest": {
    "preset": "jest-react-native"
  },
  "devDependencies": {
    "babel-jest": "16.0.0",
    "babel-preset-react-native": "1.9.0",
    "jest": "16.0.2",
    "jest-react-native": "16.1.0",
    "react-test-renderer": "15.3.2"
  }
}
```

And tried both linking using react-native and nrpm which both tells me that the linking was successful.

Would much appreciate some help with this.

 Cheers,

**Comment by julesmoretti** [comment] 2016-11-11 01:04
Still going on... anyone? @brentvatne @chengyin @MoOx @mattapperson @gorangajic ?

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.769 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by Fouppy** [comment] 2016-11-11 01:16
Just encountered the same issue, simply clean your builds:
```
cd android
./gradlew clean
```

**Comment by julesmoretti** [comment] 2016-11-11 06:16
@Fouppy - Merci! This is a good temporary fix... but does not feel like a permanent one.

Because this has to be run every time you you rebuild from scratch the android folder:

```
rm -Rf node_modules
rm -Rf android
rm -Rf __tests__

npm i
react-native android
react-native run-android // <== might not be nessessary
react-native link // <== extra steps
cd android && ./gradlew clean // <== extra steps
react-native build // <== extra steps
```

Would be dope if you guys could make sure that these steps were not required ;)

**Comment by fabien-h** [comment] 2017-06-14 22:04
Did all of that. Still get :

    /Users/fabien/projects/lecito/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:17: error: cannot find symbol
    import com.facebook.yoga.YogaNodeAPI;
                            ^
      symbol:   class YogaNodeAPI
      location: package com.facebook.yoga
    /Users/fabien/projects/lecito/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:34: error: cannot find symbol
                    YogaNodeAPI node,
                    ^
      symbol: class YogaNodeAPI
    2 errors
    :react-native-svg:compileReleaseJavaWithJavac FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':react-native-svg:compileReleaseJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

**Comment by aschwizzy710** [comment] 2017-06-15 02:12
Same as the above

**Comment by aschwizzy710** [comment] 2017-06-15 02:12
![screenshot 2017-06-14 22 06 51](https://user-images.githubusercontent.com/18079132/27162319-98c2f814-514e-11e7-9092-59c40cf93799.png)

**Comment by joncursi** [comment] 2017-07-22 01:04
@aschwizzy710 I'm getting the same error as you. Did you happen to figure it out why react-native can't compile `react-native-svg` on android?

**Comment by DavitVosk** [comment] 2017-12-20 15:43
The same problem here. cd android && ./gradlew clean does not help

**Comment by DavitVosk** [comment] 2017-12-20 16:13
Solved.

Make sure you have same versions for

    compileSdkVersion 25
    buildToolsVersion '25.0.0'
and

compile "com.android.support:appcompat-v7:25.0.0"
in your android/app/build.gradle
As described here https://stackoverflow.com/a/42144590

**Comment by msand** [comment] 2018-02-11 23:24
This has probably been caused by incompatible versions. Closing for now.

**Closed by msand** 2018-02-11 23:24 UTC
