### ISSUE TITLE
check the render method of `G`

### ISSUE THREAD

**Issue by sms1989** [react-native-community/react-native-svg#537] opened 2017-12-08 14:35 UTC
after update react native to 0.50.0 and 0.51.0

i have this error now: "check the render method of \`G\`"

![screenshot_1512743565](https://user-images.githubusercontent.com/4324993/33770277-41607dce-dc42-11e7-8b9d-d34844fb7e83.png)

"react": "16.0.0",
"react-native": "0.50.0",
"react-native-svg": "^6.0.0-rc1",

**Comment by dustinsavery** [comment] 2017-12-08 23:50
Can you post what you have for that element? I have a feeling I know what the issue is (it's a propType issue).

**Comment by sms1989** [comment] 2017-12-09 22:29
My Svg works fine in new app (new RN app). but for old app after update to RN 0.50.0 or above this issue is appear.

this is my element:
```
<Svg
  height="150"
  width="150"
  viewBox="0 0 512 512"
>
  <G>
	  <Path
	  fill="#FFF"
	  d="M409.2,260.1c-7.2,0-13.1,5.9-13.1,13.1c0,7.2,5.9,13.1,13.1,13.1c7.2,0,13.1-5.9,13.1-13.1
	  C422.3,266,416.4,260.1,409.2,260.1z M409.2,282.6c-5.2,0-9.4-4.2-9.4-9.4c0-5.2,4.2-9.4,9.4-9.4s9.4,4.2,9.4,9.4
	  C418.6,278.4,414.4,282.6,409.2,282.6z M407.4,300.2c-1.1-0.3-2.3-0.5-3.4-0.5h0c-5.5,0-10.5,3.5-12.4,8.7l-0.1,0.1l0,0.2l0,0.2
	  c-0.1,0.4-0.2,0.8-0.3,1.2c0,0,0,0,0,0l0,0.1l0,0.3c-0.6,3.2,0,6.6,1.8,9.4c1.8,2.8,4.5,4.8,7.7,5.7c1.1,0.3,2.3,0.5,3.4,0.5
	  c5.9,0,11.1-4,12.7-9.7C418.5,309.3,414.4,302,407.4,300.2z M413,315.3c-1.1,4.2-4.9,7-9.1,7c-0.8,0-1.6-0.1-2.4-0.3
	  c-4.8-1.3-7.7-6-6.8-10.7c0,0,0,0,0,0c0.1-0.5,0.3-1,0.4-1.5c1.4-3.8,4.9-6.2,8.8-6.2c0.8,0,1.6,0.1,2.4,0.3
	  C411.4,305.1,414.4,310.3,413,315.3z M395.2,338.4c-2-1.2-4.3-1.8-6.6-1.8c-4.4,0-8.5,2.2-10.9,5.8l-0.1,0.1l-0.1,0.1
	  c-0.2,0.3-0.4,0.7-0.6,1l-0.1,0.1l0,0.1l-0.1,0.2l-0.1,0.2c-1.4,2.9-1.6,6.2-0.7,9.3c1,3.2,3.1,5.9,6,7.6c2,1.2,4.3,1.8,6.6,1.8
	  c4.7,0,9-2.5,11.4-6.6C403.7,350.1,401.5,342.1,395.2,338.4z M396.8,354.5c-1.7,3-4.9,4.7-8.1,4.7c-1.6,0-3.2-0.4-4.7-1.3
	  c-4.3-2.5-5.9-7.8-3.7-12.2c0,0,0,0,0,0c0.2-0.4,0.4-0.7,0.6-1.1c1.8-2.7,4.8-4.1,7.8-4.1c1.6,0,3.2,0.4,4.7,1.3
	  C397.9,344.3,399.4,350,396.8,354.5z M256,321.4c-8,0-14.5,6.5-14.5,14.5s6.5,14.5,14.5,14.5c8,0,14.5-6.5,14.5-14.5
	  S264,321.4,256,321.4z M256,346.6c-5.9,0-10.8-4.8-10.8-10.8s4.8-10.8,10.8-10.8s10.8,4.8,10.8,10.8S261.9,346.6,256,346.6z
	  M337.3,240.1c-18.3,0-33.1,14.9-33.1,33.1s14.9,33.1,33.1,33.1c18.3,0,33.1-14.9,33.1-33.1S355.6,240.1,337.3,240.1z M337.3,302.6
	  c-16.2,0-29.4-13.2-29.4-29.4s13.2-29.4,29.4-29.4c16.2,0,29.4,13.2,29.4,29.4S353.5,302.6,337.3,302.6z M373.6,372.3
	  c-2.5-2.5-5.8-3.8-9.3-3.8c-3.5,0-6.7,1.3-9.2,3.8l0,0l0,0l0,0c-26.5,26.5-61.6,41-99,41c-77.2,0-140.1-62.8-140.1-140.1
	  c0-77.2,62.8-140.1,140.1-140.1c7.2,0,13.1-5.9,13.1-13.1c0-7.2-5.9-13.1-13.1-13.1H99.7c-5.5,0-10,4.5-10,10v46.9
	  c0,7.2,5.9,13.1,13.1,13.1c7.2,0,13.1-5.9,13.1-13.1v-28.1c0-1.4,1.1-2.5,2.5-2.5h47.8c-21,13.5-38.9,31.6-52,53
	  c-7.9,12.8-14,26.6-18.1,41.1c-4.3,14.9-6.4,30.4-6.4,46c0,22.5,4.4,44.2,13.1,64.7c4.2,9.9,9.3,19.4,15.3,28.3
	  c6,8.8,12.8,17.1,20.3,24.6c7.5,7.5,15.8,14.4,24.6,20.3c8.9,6,18.4,11.2,28.3,15.3c20.5,8.7,42.3,13.1,64.7,13.1
	  c22.4,0,44.2-4.4,64.6-13c9.8-4.2,19.3-9.3,28.2-15.3c8.8-5.9,17.1-12.7,24.6-20.2l0.1-0.1c0,0,0.1-0.1,0.1-0.1c0,0,0.1-0.1,0.1-0.1
	  l0.1-0.1l0,0l0,0c2.4-2.5,3.6-5.8,3.6-9.2C377.4,377.9,376.1,374.7,373.6,372.3z M371.1,388c-0.1,0.1-0.1,0.1-0.2,0.2
	  s-0.1,0.1-0.2,0.2c-29.4,29.3-70,47.4-114.8,47.4c-89.8,0-162.6-72.8-162.6-162.6c0-62.4,35.1-116.6,86.7-143.8h-61.7
	  c-3.5,0-6.3,2.8-6.3,6.3v28.1c0,5.2-4.2,9.4-9.4,9.4c-5.2,0-9.4-4.2-9.4-9.4v-46.9c0-3.5,2.8-6.3,6.3-6.3H256c5.2,0,9.4,4.2,9.4,9.4
	  c0,5.2-4.2,9.4-9.4,9.4c-79.4,0-143.8,64.4-143.8,143.8S176.6,417,256,417c39.7,0,75.7-16.1,101.7-42.1l0.1-0.1
	  c1.8-1.8,4.2-2.7,6.6-2.7c2.4,0,4.8,0.9,6.6,2.7C374.6,378.5,374.6,384.3,371.1,388z M386.8,252.3c-2.7-6.4-6.6-12.2-11.5-17.1
	  s-10.7-8.8-17.1-11.5c-6.6-2.8-13.7-4.2-20.9-4.2c-2,0-4,0.1-6,0.3l37-37l13.3-13.3l4.5-4.5c2.4-2.4,3.8-5.7,3.8-9.1
	  c0-3.4-1.2-6.7-3.6-9.2l0,0l0,0l-0.1-0.1c0,0-0.1-0.1-0.1-0.1c0,0-0.1-0.1-0.1-0.1l-0.1-0.1l0,0l0,0c-2.4-2.3-5.7-3.6-9-3.6
	  c-3.5,0-6.8,1.4-9.3,3.8l-4.3,4.3L349.9,164L310,203.9c0,0-0.1,0.1-0.1,0.1l-0.1,0.1l0,0l0,0v-21.6c0-7.2-5.9-13.1-13.1-13.1
	  s-13.1,5.9-13.1,13.1v90.7c0,15.2-12.3,27.5-27.5,27.5c-15.2,0-27.5-12.3-27.5-27.5c0-11.3-3.5-22.2-10.1-31.4
	  c-4.9-6.8-11.4-12.4-18.8-16.3c-7.6-4-16.3-6.1-24.9-6.1c-7.2,0-14.3,1.4-20.9,4.2c-6.4,2.7-12.1,6.5-17.1,11.5
	  c-4.9,4.9-8.8,10.6-11.5,17c-2.8,6.6-4.3,13.6-4.3,20.8c0,0.1,0,0.2,0,0.3c0,0.1,0,0.2,0,0.4c0.1,3.4,1.5,6.6,4,9
	  c2.5,2.4,5.7,3.7,9.2,3.7c7.2,0,13.1-5.9,13.1-13.1c0-15.2,12.3-27.5,27.5-27.5c15.2,0,27.5,12.3,27.5,27.5
	  c0,11.3,3.5,22.2,10.1,31.4c3.7,5.1,8.4,9.7,13.6,13.2c-3.2,5.4-4.9,11.5-4.9,17.9c0,9.4,3.6,18.1,10.3,24.8
	  c6.6,6.6,15.4,10.3,24.8,10.3c9.4,0,18.1-3.6,24.8-10.3c6.6-6.6,10.3-15.4,10.3-24.8c0-6.4-1.7-12.5-4.9-17.9
	  c3.9-2.6,7.5-5.8,10.6-9.4c4.4,5.1,9.8,9.3,15.7,12.4c7.6,4,16.3,6.1,24.9,6.1c7.3,0,14.3-1.4,20.9-4.2c6.4-2.7,12.2-6.6,17.1-11.5
	  s8.8-10.7,11.5-17.1c2.8-6.6,4.2-13.7,4.2-20.9S389.6,258.9,386.8,252.3z M312.5,206.7c0.1-0.1,0.1-0.1,0.2-0.2l39.9-39.9l13.3-13.3
	  l4.3-4.3c1.8-1.8,4.2-2.7,6.6-2.7c2.3,0,4.6,0.9,6.5,2.6c0.1,0.1,0.1,0.1,0.2,0.2c0.1,0.1,0.1,0.1,0.2,0.2c3.5,3.7,3.4,9.5-0.2,13.1
	  l-4.5,4.5l-13.3,13.3l-39.7,39.7c-0.4,0.4-0.8,0.8-1.3,1.1c-1.8,0.4-3.7,1-5.5,1.6c0,0-0.1,0-0.1,0c-2.3-0.1-4.6-1-6.4-2.7
	  C309.1,216.2,309,210.4,312.5,206.7z M309.8,222.3c0.1,0.1,0.2,0.2,0.2,0.2c1,1,2.2,1.9,3.5,2.5c-1.3,0.6-2.5,1.3-3.7,2V222.3z
	  M337.3,323.2c-16.7,0-31.6-8.2-40.6-20.9c-4.2,5.8-9.6,10.7-15.9,14.3c4.1,5.3,6.5,11.9,6.5,19.1c0,17.3-14,31.3-31.3,31.3
	  s-31.3-14-31.3-31.3c0-7.2,2.4-13.8,6.5-19.1c-6.3-3.6-11.7-8.5-15.9-14.3c-5.9-8.2-9.4-18.3-9.4-29.2c0-17.3-14-31.3-31.3-31.3
	  s-31.3,14-31.3,31.3c0,5.2-4.2,9.4-9.4,9.4c-5.1,0-9.2-4.1-9.4-9.1c0-0.1,0-0.2,0-0.2c0-0.1,0-0.2,0-0.2c0.1-27.5,22.5-49.8,50-49.8
	  c16.7,0,31.6,8.2,40.6,20.9c5.9,8.2,9.4,18.3,9.4,29.2c0,17.3,14,31.3,31.3,31.3s31.3-14,31.3-31.3v-90.7c0-5.2,4.2-9.4,9.4-9.4
	  s9.4,4.2,9.4,9.4v51.6c4.1-3.3,8.7-5.9,13.7-7.8c2.3-0.1,4.4-0.7,6.4-1.9c3.6-0.8,7.3-1.3,11.2-1.3c27.6,0,50,22.4,50,50
	  C387.3,300.8,364.9,323.2,337.3,323.2z"
	  />
	</G>
</Svg>
```

**Comment by dustinsavery** [comment] 2017-12-10 19:47
That’s really bizarre and not at all what I was thinking it was. . So that SVG works on a fresh project with matching dependencies? If that’s the case, it could be pointing at the wrong place.

**Comment by jmsims2** [comment] 2018-03-05 03:09
I've got the same issue with a project I just created with create-react-native-app.  Every issue I find gives a fix of going into xcode but I'm using expo.  Is this an issue with this package or maybe I'm somehow screwing this up?

"expo": "^25.0.0",
"react": "16.2.0",
"react-native": "0.52.0",

**Comment by msand** [comment] 2018-12-09 03:41
Please provide a full repo as a reproduction. Closing until then.

**Closed by msand** 2018-12-09 03:41 UTC
