### ISSUE TITLE
How to set SVG width and height in percents?

### ISSUE THREAD

**Issue by iyel** [react-native-community/react-native-svg#3] opened 2016-02-20 22:24 UTC
Hi! Is there way to set width for e.g to 100%?

**Comment by magicismight** [comment] 2016-02-22 01:13
Can\`t do that in react-native.
SVG like other components in react-native.
It can\`t set dimensions [style](http://facebook.github.io/react-native/docs/style.html#content) in percent.

**Comment by ipmcc** [comment] 2018-02-05 15:47
I hit this problem too. And FWIW, I've had no problem specifying height and width using percents in other React Native components. The problem with the `Svg` element here is that it deliberately sanitizes the height and width parameters, with this code in `render()`:
```
        const {opacity, width, height, viewBox, preserveAspectRatio, style, ...props} = this.props;
        let dimensions;

        if (width && height) {
            dimensions = {
                width: +width,
                height: +height,
                flex: 0
            };
        }
```

I'm guessing that the `+` coerces the value to a number, making percent values into `NaN`. I found that if I removed the `+` everything worked as expected. I expect RN to have standardized sanitization for width and height values, and I'm not sure why the `Svg` element feels the need to do anything additional.

**Comment by msand** [comment] 2018-02-05 16:53
Apparently, support came about a year ago: https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11
Feel free to make a PR, otherwise I'll come around to changing this after testing it out.

**Comment by unimonkiez** [comment] 2018-03-03 15:19
@msand This give man a cookie!

**Comment by mlazari** [comment] 2018-04-21 18:00
@msand percentages in width & height work on iOS, but on Android I'm seeing this error:
`SurfaceView should have explicit width and height set`
Any ideas?

**Comment by msand** [comment] 2018-04-21 18:14
@mlazari Are you using Expo? I think they have an earlier version, from before the percent support was merged.

**Comment by mlazari** [comment] 2018-04-21 19:29
@msand No, I don't use Expo. I had version 6.2.2 and updated now to 6.3.1, but still seeing the error. I tried to reproduce it in a new sample project, but there it works, so it must be something in my project.

**Comment by msand** [comment] 2018-04-22 09:10
Have you tried cleaning the android build?
cd android
gradlew clean

**Closed by msand** 2018-04-22 09:10 UTC

**Comment by mlazari** [comment] 2018-04-23 06:00
@msand Cleaning the project doesn't change anything. I can reproduce the error message in a new project with something like this:

render() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <View style={{ flex: 1 }}>
        <MySVGComponent style={{ width: '50%', height: '100%' }} />
      </View>
    </View>
  );
}

On iOS it's simply not visible (because the inner View has width 0), but doesn't show any errors. On Android it's showing "SurfaceView should have explicit width and height set" error.
In my project the width / height of the container is not zero, but I get the same error.
