### ISSUE TITLE
render svg crash app on Android

### ISSUE THREAD

**Issue by fedeerbes** [react-native-community/react-native-svg#689] opened 2018-05-15 16:32 UTC
Hi, since yesterday, we have this error on react native android [19262](https://github.com/facebook/react-native/issues/19262). 

I fixed with the workaround ("com.facebook.react:react-native:0.49.5") { force = true } en android/app/gradle.build

but when i do it, on every render of svg my app crash. If the svg is commented work fine 

# Environment
Environment:
OS: macOS High Sierra v10.13
Node: 9.4.0
Android Studio: Not Found

Packages: (installed)
"react": "16.0.0-beta.5"
"react-native": "0.49.5",
"react-native-svg": "5.5.1",

# Steps to Reproduce
Fix the probleme of [19262](https://github.com/facebook/react-native/issues/19262) and build android .apk normally 

# Actual Behavior
App crash on svg render

# Stack trace error on android studio
05-15 13:04:17.288 16375-16375/com.packageName E/BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
05-15 13:04:17.558 16375-16420/com.packageName E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                          Process: com.packageName, PID: 16375
                                                          java.lang.NoSuchMethodError: No virtual method getChildAt(I)Lcom/facebook/react/uimanager/ReactShadowNodeImpl; in class Lcom/horcrux/svg/SvgViewShadowNode; or its super classes (declaration of 'com.horcrux.svg.SvgViewShadowNode' appears in /data/app/com.packageName-1/base.apk)
                                                              at com.horcrux.svg.SvgViewShadowNode.drawChildren(SvgViewShadowNode.java:139)
                                                              at com.horcrux.svg.SvgViewShadowNode.drawOutput(SvgViewShadowNode.java:119)
                                                              at com.horcrux.svg.SvgViewShadowNode.onCollectExtraUpdates(SvgViewShadowNode.java:103)
                                                              at com.facebook.react.uimanager.ReactShadowNode.dispatchUpdates(ReactShadowNode.java:300)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:866)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
                                                              at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:604)
                                                              at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:570)
                                                              at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:531)
                                                              at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:136)
                                                              at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:143)
                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                              at java.lang.Thread.run(Thread.java:762)

**Comment by dugin** [comment] 2018-05-15 20:39
Same issue here

**Comment by francescosessa-eclettica** [comment] 2018-05-15 22:49
Same issue
react-native 0.49.5
react 16.2.0
react-native-svg 5.4.1

**Comment by fedeerbes** [comment] 2018-05-16 03:30
Hi @guilharj, this workaround needs to be set on every gradle of each native dependence? Or just in android/app/gradle.build. Thanks for sharing this info, means a lot

**Comment by guilharj** [comment] 2018-05-16 03:50
only on you main app..  not inside the others..  So I did like this and worked fine

**Comment by koswarabilly** [comment] 2018-05-16 04:49
crash on real device

**Comment by sajjukarki123** [comment] 2018-05-16 07:56
Same issue since yesterday
react-native 0.45.1
react 16.0.0-alpha.12
react-native-svg 5.2.0

**Comment by huowenxuan** [comment] 2018-05-16 07:59
There is a temporary solution.
react-native-svg build.gradle

`
dependencies {
    compile ("com.facebook.react:react-native:your-react-native-version") { force = true } // From node_modules
}
`

**Comment by sajjukarki123** [comment] 2018-05-16 08:10
@huowenxuan  but this is the fix for development server returning a response of 404. is not it? The issue is the app crashes as soon as it tries to render svg element.

**Comment by huowenxuan** [comment] 2018-05-16 08:12
@sajjukarki123 But it does solve the problem.😂

**Comment by sajjukarki123** [comment] 2018-05-16 08:15
No luck for me then. I also tried the solution from @guilharj , still the app is crashing as soon as it renders svg. Works fine if I comment the code for rendering svg.  :(

**Comment by sajjukarki123** [comment] 2018-05-16 08:40
@huowenxuan yea it worked. My fault, was updating just the bundle of main app. but should update from the respective library that throwing also the override issue while building.

**Comment by ichiyouji** [comment] 2018-05-16 09:15
@sajjukarki123 thanks for the insight, it works, but still, the approach is kinda hacky in my opinion to change the configuration inside each library (I made changes on the `build.gradle` inside respective `node_modules` library or did I misinterpret something?)

**Comment by sajjukarki123** [comment] 2018-05-16 09:42
Yes, you are right @ichiyouji . I hope its a temporary solution until we find something better without making changes to the node_module.

**Comment by fedeerbes** [comment] 2018-05-16 11:48
Thanks @guilharj it worked with your workaround! =)

**Comment by leofontes** [comment] 2018-05-16 12:36
@guilharj I tried like this but it complains that exclude doesn't exist

`    implementation project(':react-native-contacts') {
        exclude group: 'com.facebook.react', module: 'react-native'
    }`

Error:FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Leo/Documents/Pingo/app/android/app/build.gradle' line: 153

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method exclude() for arguments [{group=com.facebook.react, module=react-native}] on project ':react-native-contacts' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by guilharj** [comment] 2018-05-16 12:48
@leofontes  try to  do like this

implementation **(** project(':react-native-contacts') **)**{ exclude group: 'com.facebook.react', module: 'react-native' }

**Comment by JordanDuncan** [comment] 2018-05-16 14:33
I fixed this in my 0.47.2 app by making sure my `allProjects` entry in `android/build.gradle` looks like:

```
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.react:react-native:0.47.2' // <-- add this
            }
        }
        ...
    }
}
```

...and I added the following to my `android/app/build.gradle` file under `dependencies`:

```
dependencies {
    compile ("com.facebook.react:react-native:0.47.2"){
        force = true;
    }
   ...
}
```

You'll need to swap out 0.47.2 in both with your apps RN version but building/running was all good after these changes.

**Comment by CristianeMayara** [comment] 2018-05-16 15:51
I followed the approach of @guilharj and it worked fine. The solution worked for a real device.

react-native 0.49.3
react 16.0.0-beta.5
react-native-svg 5.4.2

**Comment by RoarRain** [comment] 2018-05-17 02:16
Could not find method exclude() for arguments [{group=com.facebook.react, module=react-native}] on project ':react-native-svg' of type org.gradle.api.Project

**Comment by ichiyouji** [comment] 2018-05-17 02:33
@RoarRain check @guilharj's comment above, you might be missing extra bracket when typing

implementation **(** project(':react-native-contacts') **)** {
    exclude group: 'com.facebook.react', module: 'react-native'
}

**Comment by RoarRain** [comment] 2018-05-17 02:48
@ichiyouji thank you very much! it is work. i am so careless.

**Comment by BeHotSiii** [comment] 2018-06-14 08:32
Unfortunately I still got the same issue.

react-native 0.55.4
react 16.3.1
react-native-svg 6.3.1

I already tried the solutions provided by @guilharj and @JordanDuncan, but the app keeps crashing every time I try to render a svg.

My android build.gradle:
```
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.react:react-native:0.55.4'
            }
        }
    }
}
```

My app build.gradle:
```
dependencies {
    compile (project(':react-native-svg')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-cookie')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-image-resizer')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-fetch-blob')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-fbsdk')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile (project(':react-native-linear-gradient')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-sensitive-info')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-device-info')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-vector-icons')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-config')) { exclude group: 'com.facebook.react', module: 'react-native' }
    compile (project(':react-native-image-picker')) { exclude group: 'com.facebook.react', module: 'react-native' }


    compile "com.android.support:appcompat-v7:26.1.0"
    compile("com.facebook.react:react-native:0.55.4") {
        force = true;
    }
}
```

I tried with and without the exclude group option for each dependency in the app's build.grade, but the error still reappears.

Any ideas what might be wrong here?

**Comment by msand** [comment] 2018-12-09 01:32
@BeHotSiii Try with the latest react-native and react-native-svg versions.
Closing this until a reproduction is made available.

**Closed by msand** 2018-12-09 01:32 UTC
