### ISSUE TITLE
JSON value "0" of type NSNumber cannot be converted to Nsstring

### ISSUE THREAD

**Issue by zenggang97** [react-native-community/react-native-svg#867] opened 2018-12-07 13:27 UTC
I'm using version 8.0.0 of react-native-svg.
 When doing something as simple as this:
<BoxShadow setting={boxShadow}>
                   ....
</BoxShadow>
...
const boxShadow = {
    height: 49,
    color: '#000',
    border: 2,
    radius: 3,
    opacity: 0.2,
    x: 0,
    y: 3,
    style: { marginVertical: 5 },
}

in ios ,I get the following error:
JSON value "0" of type NSNumber cannot be converted to Nsstring

**Comment by msand** [comment] 2018-12-09 05:03
Can you provide a full replication?

**Comment by FibreFoX** [comment] 2018-12-09 15:10
Hm, that reminds me of problems I had in one of my projects, where we reverted to pre-8 version too. If I recall correctly this code did reproduce this on iOS while working on android:
```
export const burgermenu = (
    <Svg width={22} height={15}>
        <G fill="#FFF">
            <Rect x="0" y="0" width="22" height="3" />
            <Rect x="0" y="6" width="22" height="3" />
            <Rect x="0" y="12" width="22" height="3" />
        </G>
    </Svg>
)
```

**Comment by msand** [comment] 2018-12-10 02:52
@FibreFoX That seems to work fine for me in both android and ios. Closing this until a reproduction is available.

**Closed by msand** 2018-12-10 02:52 UTC
Labels: question

**Comment by KidkArolis** [comment] 2019-01-10 22:53
I'm getting this as well with the Usage example from README..
If I "Dismiss" the React error, I do see the svg, but the error keeps happening upon reload.

**Comment by KidkArolis** [comment] 2019-01-10 23:02
I've downgraded to v7, but got the same error.

If I remove `<Rect>` it works, e.g.:

This works:

```
<Svg width={100} height={100} viewBox="0 0 100 100">
          <Circle
            cx="50"
            cy="50"
            r="45"
            stroke="blue"
            strokeWidth="2.5"
            fill="green"
          />
        </Svg>
```

This doesn't:

```
<Svg width={100} height={100} viewBox="0 0 100 100">
          <Rect
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
          />
        </Svg>
```

**Comment by AdamGerthel** [comment] 2020-02-27 10:18
I'm getting the same error in an existing project after upgrading from v9.13.3 (to 11). There's no indication on what's triggering the error. I have quite a lot of different SVG elements. Does anyone have *any* indication on what it could be caused by?

**Comment by ljybill** [comment] 2021-04-13 07:07
> I'm getting the same error in an existing project after upgrading from v9.13.3 (to 11). There's no indication on what's triggering the error. I have quite a lot of different SVG elements. Does anyone have _any_ indication on what it could be caused by?

try react-native-svg@^10.0.0

**Comment by chakrihacker** [comment] 2021-05-10 05:54
Facing this issue when trying to animate via percentage
